leezer3/OpenBVE

openBVE/OpenBve/Graphics/Screen.cs
openBVE/OpenBve/OldCode/MainLoop.cs
openBVE/OpenBve/OldCode/NewCode/GameWindow.cs
openBVE/OpenBve/System/Input/ProcessControls.cs

Contains these changes:
- Allow resizing and closing window with loading screen
- change OpenGL window title from "OpenBve" to "openBVE"
- fix route information form under Mono
- implement RouteInfoActive as a property (RouteInformationForm.Visible)

Windowing related enhancements and fixes

---

openBVE/OpenBve/System/Input/ControlRepeats.cs

Fix infinite key repeating

---

openBVE/OpenBve/OpenBve.csproj

Related to issue #9 (path isn't configurable yet). Please test it on Windows/Visual Studio because I'm afraid it could discard this hack.

Fix OpenBve.csproj on xbuild

---

.gitignore
ObjectViewer/.gitignore
RouteViewer/.gitignore
TrainEditor/.gitignore
openBVE/OpenBve/.gitignore
openBVE/OpenBveApi/.gitignore
openBVE/OpenBveAts/.gitignore
openBVE/Sound.Flac/.gitignore
openBVE/Sound.RiffWave/.gitignore
openBVE/Texture.Ace/.gitignore
openBVE/Texture.BmpGifJpegPngTiff/.gitignore

Improve .gitignore:
- using a single top-level file
- ignoring some of the auto-generated files

Improve .gitignore

---

openBVE/OpenBve/Game/Menu.cs
openBVE/OpenBve/OldCode/MainLoop.cs
openBVE/OpenBve/OldCode/NewCode/GameWindow.cs

- Mouse movements select the menu item under the mouse
- Mouse left click fires the menu item

Add mouse support for in-game menu

---

openBVE/OpenBve/Data/Languages/ca-ES.cfg
openBVE/OpenBve/Data/Languages/es-ES.cfg

I have updated both the Catalan and Spanish language files to include the translations of strings added recently. Older strings were also corrected.

Updated Catalan and Spanish translations

---

openBVE/OpenBve/OpenBve.csproj

This fixes issue #29. I suspect that the latter PostBuildEvent has overridden the previous one.

Fix Data folder copying bug

---

openBVE/OpenBve/System/Functions/FileSystem.cs

Revert "Remove localization from UserData path"

---

openBVE/OpenBve/Data/Languages/cs-CZ.cfg

I've updated Czech translation. I hope there are no more untranslated strings.

Update Czech translation

---

openBVE/OpenBve/OldCode/Loading.cs
openBVE/OpenBve/OldCode/TrackManager.cs
openBVE/OpenBve/OldCode/TrainManager.cs
openBVE/OpenBve/OldParsers/ExtensionsCfgParser.cs
openBVE/OpenBve/OldParsers/TrainDatParser.cs
openBVE/OpenBve/System/Functions/Illustrations.cs
openBVE/OpenBve/System/Input/ProcessControls.cs

This is working OK, and appears ready to merge.
I cannot reproduce the bogies visible from cab issue mentioned in the last comment here:
https://github.com/leezer3/OpenBVE/issues/50#issuecomment-198723576

Merge BogieMotion branch into mainline

---

openBVE/OpenBve/OldCode/FunctionScripts.cs
openBVE/OpenBve/OldCode/ObjectManager.cs
openBVE/OpenBve/OldParsers/AnimatedObjectParser.cs

This adds a new function to animated objects:
TrackFollowerFunction
This allows animated objects to be moved following Rail0 in exactly the same way as any other animated object function.

Add TrackFollowerFunction to animated objects

---

openBVE/OpenBve/OldCode/Loading.cs
openBVE/OpenBve/OpenBve.csproj
openBVE/OpenBve/Parsers/Bve5ScenarioParser.Commands.cs
openBVE/OpenBve/Parsers/Bve5ScenarioParser.Components.cs
openBVE/OpenBve/Parsers/Bve5ScenarioParser.Functions.cs
openBVE/OpenBve/Parsers/Bve5ScenarioParser.cs
openBVE/OpenBve/System/Functions/Extensions.cs
openBVE/OpenBve/System/Program.cs
openBVE/OpenBve/UserInterface/formMain.Start.cs

- Improved character encoding detection
- Route image is now displayed in route selection menu
- Less strict file version check
- Better handling of comments
The scenario file detector code for the main menu is not included, but I will upload it once I am sure it is stable.

[BVE5] Character encoding tweaks and more

---

openBVE/OpenBve/Graphics/Renderer/Functions.cs
openBVE/OpenBve/Graphics/Renderer/Lighting.cs
openBVE/OpenBve/OldCode/NewCode/GameWindow.cs
openBVE/OpenBve/OldCode/TrainManager.cs
openBVE/OpenBve/OldParsers/BveRouteParser/CsvRwRouteParser.cs
openBVE/OpenBve/OpenBve.csproj
openBVE/OpenBve/Parsers/DynamicLightParser.cs

This requires a new command: **Route.DynamicLight(_Light.xml_)**
_Light.xml_ points to an XML descriptor file describing the brightness at different times of day.
https://github.com/leezer3/OpenBVE/issues/90
Overrides Route.AmbientLight, Route.DirectionalLight and Route.LightDirection
Sample lighting XML file:
```
<?xml version="1.0" encoding="utf-8"?>
<openBVE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Brightness>
<Time>00.00</Time>
<AmbientLight>0,0,0</AmbientLight>
<DirectionalLight>0,0,0</DirectionalLight>
<LightDirection>0.223606797749979, 0.86602540378444, -0.447213595499958</LightDirection>
</Brightness>
<Brightness>
<Time>06.00</Time>
<AmbientLight>160,160,160</AmbientLight>
<DirectionalLight>160,160,160</DirectionalLight> …
```

Implement basic dynamic lighting model

---

ObjectViewer/ProgramS.cs
ObjectViewer/System/GameWindow.cs
RouteViewer/Fonts.cs
RouteViewer/InterfaceR.cs
RouteViewer/LoadingR.cs
RouteViewer/Options.cs
RouteViewer/ProgramR.cs
RouteViewer/Properties/AssemblyInfo.cs
RouteViewer/Renderer.Loading.cs
RouteViewer/Renderer.Primitives.cs
RouteViewer/Renderer.Strings.cs
RouteViewer/RendererR.cs
RouteViewer/RouteViewer.csproj
RouteViewer/System/Gamewindow.cs
RouteViewer/TextureManager.cs
RouteViewer/formOptions.Designer.cs
RouteViewer/formOptions.cs
openBVE/OpenBve/Graphics/Textures.cs

- RouteViewer now has a loading screen, which can optionally include the main program loading screen pictures, a progress bar & the openBVE logo.
- Object Viewer now allows for the mousewheel to be used for zoom. https://github.com/leezer3/OpenBVE/issues/110

Improve Viewer Applications

---

openBVE/OpenBve/Data/Languages/ca-ES.cfg

Fixed some unstranslated strings in Package Management

Updated ca_ES translation

---

Readme.md

Trivial change to try another pull request. Is this is how you wanted me to work?
Cheers.

Added Travis badge for the master branch.

---

source/OpenBVE/Simulation/TrainManager/Doors.cs
source/OpenBVE/Simulation/TrainManager/Station.cs
source/OpenBVE/System/Input/ProcessControls.cs
source/OpenBveApi/Runtime.cs

DoorInterlockState extended from two states (locked and unlocked) to four (locked, left, right, unlocked).
#143

Partial door interlocking

---

source/OpenBVE/OpenBve.csproj
source/OpenBVE/Properties/AssemblyInfo.sh

Also fixed sh formatting. See #148

Fix problems with building without the VS Modelling SDK.

---

makefile

Sorry for the second PR, but I missed some lingering issues not caught by #160.

Fix lingering dependency and formatting issues in makefile

---

source/ObjectViewer/ProgramS.cs
source/ObjectViewer/System/GameWindow.cs
source/OpenBVE/OldCode/NewCode/GameWindow.cs
source/RouteViewer/ProgramR.cs
source/RouteViewer/RendererR.cs
source/RouteViewer/System/Gamewindow.cs

Closes https://github.com/leezer3/OpenBVE/issues/109
Untested on anything other than Windows at the minute, but will do so later tomorrow.

Add Drag and Drop support for Route Viewer and Object Viewer

---

source/OpenBVE/OldCode/PluginManager.cs
source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Base.cs
source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Bve2.cs
source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Bve4.cs
source/OpenBVE/Parsers/SoundConfiguration/SoundCfg.Xml.cs

Don't hardcode sound files of the default ATS plugin

---

source/OpenBVE/Graphics/Screen.cs

Add small delay after switching to full screen

---

source/OpenBVE/Graphics/Renderer.cs
source/OpenBVE/Graphics/Renderer/Overlays.HUD.cs
source/OpenBVE/System/Input/ProcessControls.cs

This PR makes it possible to show gradient as permil.

New: Show gradient as permil

---

source/OpenBVE/Simulation/TrainManager/Train/Horn.cs

If StartSound doesn't exist, play LoopSound immediately.

Change: Behavior when StartSound doesn't exit

---

documentation/HTML/menu.html
documentation/HTML/route_csv.html
documentation/HTML/route_stationxml.html
documentation/HTML/train_train_dat.html

This PR add documentation of parameters that something gets caught in the door.

New: Add documentation of parameters that something gets caught in the door

---

source/ObjectViewer/Parsers/XObjectParser.cs
source/OpenBVE/Parsers/Object/Generic/XObjectParser.cs
source/RouteViewer/Parsers/XObjectParser.cs

This PR fix issue that some X files fail to read. (#277)

Fix: Issue that some X files fail to read

---

OpenBVE.sln
makefile
source/Plugins/Texture.Tga/Plugin.Parser.cs
source/Plugins/Texture.Tga/Plugin.cs
source/Plugins/Texture.Tga/Properties/AssemblyInfo.cs
source/Plugins/Texture.Tga/Texture.Tga.csproj

Done a little mangling on a TGA image loader:
http://www.codeproject.com/Articles/31702/NET-Targa-Image-Reader
This now works and loads images into openBVE quite nicely.
Any thoughts?
Biggest concern is that this licence is GPL/ FSF incompatible ( http://www.gnu.org/licenses/license-list.en.html#cpol )
Whilst we're public domain, this would probably make the plugin non-available for use in any potential Debian repository builds.
Problem looking for a solution?

TGA image loader

---

source/AssimpXParser/XFileParser.cs

This PR fix an issue where parsing failed with some X files at AssimpXParser.
https://github.com/leezer3/OpenBVE/pull/280#issuecomment-441667168
However, since the number of vertices is 0, an exception "nVertices must be greater than zero" will occur ...

Fix: Issue where parsing failed with some X files at AssimpXParser

---

source/ObjectViewer/ProgramS.cs
source/ObjectViewer/formTrain.cs

This PR fixes #311 problems occurring on Linux.
On Linux, the Train settings window was not displayed.

Fix: issue with ObjectViewer on #311

---

source/OpenBVE/Parsers/Panel/PanelAnimatedXmlParser.cs
source/OpenBVE/Parsers/Panel/PanelXmlParser.cs

https://github.com/leezer3/OpenBVE/pull/317#pullrequestreview-207107355

Fix: add zero node check at PanelXmlParser and PanelAnimatedXmlParser

---

source/CarXMLConvertor/CarXMLConvertor.csproj
source/CarXMLConvertor/Convert.ExtensionsCfg.cs
source/CarXMLConvertor/Convert.Panel2.cs
source/CarXMLConvertor/Convert.PanelAnimated.cs
source/CarXMLConvertor/mainForm.cs
source/OpenBVE/OldCode/TrainManager.cs
source/OpenBVE/Parsers/Panel/PanelAnimatedXmlParser.cs
source/OpenBVE/Parsers/Panel/PanelXmlParser.cs
source/OpenBVE/Parsers/Train/XML/TrainXmlParser.CarNode.cs

Still needs animated panels converting too.
We could probably also automatically convert the touch zones?
Followup work to https://github.com/leezer3/OpenBVE/pull/317

Add panel conversion to CarXmlConvertor

---

source/LibRender/LibRender.csproj
source/LibRender/Objects/RenderFace.cs
source/LibRender/Renderer.Functions.cs
source/LibRender/Renderer.cs
source/ObjectViewer/RendererS.cs
source/OpenBVE/Graphics/Renderer.Loading.cs
source/OpenBVE/Graphics/Renderer.cs
source/OpenBVE/Graphics/Renderer/Background.cs
source/OpenBVE/Graphics/Renderer/Events.cs
source/OpenBVE/Graphics/Renderer/Functions.cs
source/OpenBVE/Graphics/Renderer/Lighting.cs
source/OpenBVE/Graphics/Renderer/MotionBlur.cs
source/OpenBVE/Graphics/Renderer/Overlays.cs
source/OpenBVE/Graphics/Renderer/Touch.cs
source/OpenBVE/Graphics/Screen.cs
source/OpenBVE/Simulation/World/BackgroundManager.cs
source/OpenBVE/System/GameWindow.cs
source/OpenBVE/System/Input/ProcessControls.cs
source/RouteViewer/Renderer.Loading.cs
source/RouteViewer/RendererR.cs

This moves the following to the shared renderer:
* Face rendering function
* Some reset / init functions

Shared Renderer, Part 4

---

source/OpenBveApi/Sounds/Sounds.cs

http://bveworldwide.forumotion.com/t1297p450-openbve-1-5-0-rc1-bugs#18777

Fix: issue of the audio file is not correct length

---

source/OpenBVE/OldCode/TrainManager.cs
source/OpenBVE/OpenBve.csproj
source/OpenBVE/Parsers/Script/TrackFollowingObjectParser.cs
source/OpenBVE/Parsers/Train/ExtensionsCfgParser.cs
source/OpenBVE/Parsers/Train/TrainDatParser.cs
source/OpenBVE/Parsers/Train/XML/TrainXmlParser.cs
source/OpenBVE/Simulation/TrainManager/Car/Car.Bogie.cs
source/OpenBVE/Simulation/TrainManager/Car/Car.cs
source/OpenBVE/Simulation/TrainManager/Car/Coupler.cs
source/OpenBVE/Simulation/TrainManager/Train/TrackFollowingObject.cs
source/OpenBVE/Simulation/TrainManager/Train/Train.cs
source/OpenBVE/System/GameWindow.cs
source/OpenBVE/System/Input/ProcessControls.cs
source/OpenBVE/System/Loading.cs
source/OpenBveApi/OpenBveApi.csproj
source/OpenBveApi/Train/AbstractCar.cs
source/OpenBveApi/Train/AbstractCoupler.cs
source/TrainEditor2/IO/IntermediateFile/Parser.cs
source/TrainEditor2/IO/IntermediateFile/Writer.cs
source/TrainEditor2/IO/Trains/ExtensionsCfg/Parser.cs
source/TrainEditor2/IO/Trains/ExtensionsCfg/Writer.cs
source/TrainEditor2/Models/Trains/Coupler.cs
source/TrainEditor2/ViewModels/Trains/CouplerViewModel.cs
source/TrainEditor2/Views/FormEditor.Coupler.cs
source/TrainEditor2/Views/FormEditor.Designer.cs
source/TrainEditor2/Views/FormEditor.cs

This implements the idea from the following issue: https://github.com/leezer3/OpenBVE/issues/381
Usage is simple-
In an extensions.cfg file, add the following:
```
[Coupler0]
Distances = 0.5,0.5
Object = coupler.b3d
```
In a train.xml file:
```XML
<Car>Car0.xml</Car>
<Coupler>
<Distances>0.5,0.5</Distances>
<Object>Coupler.b3d</Object>
</Coupler>
```
From a first bash about, it appears to work very nicely.
- No stretch / compression, just a moving object. (Object grow / shrink functions to be a new PR)
@s520 
Not added this to the new train editor at the minute, you're probably best to do this.
Some testing from someone else would be good too!

New: Add coupler objects

---

source/AssimpParser/X/XFileParser.cs

This PR fix issue with decompressing compressed X files.

Fix: Issue with decompressing compressed X files

---

source/TrainEditor2/IO/Panels/Bve4/Parser.cs
source/TrainEditor2/IO/Panels/Xml/Parser.cs
source/TrainEditor2/IO/Trains/ExtensionsCfg/Parser.cs
source/TrainEditor2/Models/App.cs

This PR fix an issue when importing extensions.cfg in TrainEditor2.
http://bveworldwide.forumotion.com/t1806-traineditor2-issues

Fix: an issue when importing extensions.cfg in TrainEditor2

---

source/ObjectViewer/Hosts.cs
source/ObjectViewer/ObjectManager.cs
source/Plugins/Object.Animated/Plugin.Parser.cs
source/RouteManager2/CurrentRoute.cs

This PR fix a issue that null judgment was missing.

Fix: a issue that null judgment was missing

---

source/TrainEditor2/Models/App.cs
source/TrainEditor2/Models/Trains/Motor.Simulation.cs
source/TrainEditor2/ViewModels/AppViewModel.cs
source/TrainEditor2/ViewModels/Panels/DigitalGaugeElementViewModel.cs
source/TrainEditor2/ViewModels/Panels/LinearGaugeElementViewModel.cs
source/TrainEditor2/ViewModels/Panels/NeedleElementViewModel.cs
source/TrainEditor2/ViewModels/Panels/PanelElementViewModel.cs
source/TrainEditor2/ViewModels/Panels/ThisViewModel.cs
source/TrainEditor2/ViewModels/Panels/TimetableElementViewModel.cs
source/TrainEditor2/ViewModels/Panels/TouchElementViewModel.cs
source/TrainEditor2/ViewModels/Sounds/SoundElementViewModel.cs
source/TrainEditor2/ViewModels/Trains/AccelerationViewModel.cs
source/TrainEditor2/ViewModels/Trains/BrakeViewModel.cs
source/TrainEditor2/ViewModels/Trains/CabViewModel.cs
source/TrainEditor2/ViewModels/Trains/CarViewModel.cs
source/TrainEditor2/ViewModels/Trains/CouplerViewModel.cs
source/TrainEditor2/ViewModels/Trains/DelayViewModel.cs
source/TrainEditor2/ViewModels/Trains/DeviceViewModel.cs
source/TrainEditor2/ViewModels/Trains/MotorViewModel.cs
source/TrainEditor2/ViewModels/Trains/MoveViewModel.cs
source/TrainEditor2/ViewModels/Trains/PerformanceViewModel.cs
source/TrainEditor2/ViewModels/Trains/PressureViewModel.cs
source/TrainEditor2/Views/FormEditor.Designer.cs
source/TrainEditor2/Views/FormEditor.cs
source/TrainEditor2/Views/FormEditor.resx

This PR fix a isuue with the language of TrainEditor2.
http://bveworldwide.forumotion.com/t1806-traineditor2-issues

Fix: a isuue with the language of TrainEditor2

---

source/LibRender2/Backgrounds/Background.cs
source/LibRender2/BaseRenderer.cs
source/LibRender2/Objects/ObjectLibrary.cs
source/LibRender2/Primitives/Cube.cs
source/ObjectViewer/NewRendererS.cs

This PR fix the following issues:
- the issue that an exception occurred in legacy OpenGL
- the issue that cubes were not drawn in modern OpenGL

Fix: the issue that an exception occurred in legacy OpenGL

---

source/ObjectViewer/Parsers/ExtensionsCfgParser.cs
source/ObjectViewer/ProgramS.cs
source/OpenBveApi/System/TextEncoding.cs

This PR add function to display couplers in Object Viewer.

Add: function to display couplers in Object Viewer

---

Building.md

The changes are as follows:
- Added description about GNU Make.
- Fixed the command to install NuGet client.
I searched the openSUSE build environment to solve the problem posted on the forum.
Would you like to add a note about openSUSE?

Fix: Building.md [ci skip]

---

source/LibRender2/BaseRenderer.cs
source/LibRender2/Objects/ObjectLibrary.cs
source/LibRender2/Primitives/Cube.cs
source/ObjectViewer/NewRendererS.cs
source/OpenBVE/Graphics/NewRenderer.cs
source/OpenBVE/Graphics/Renderers/Touch.cs
source/OpenBveApi/System/TextEncoding.cs

This PR fix missing touch support for legacy OpenGL.

Fix: missing touch support for legacy OpenGL

---

assets/Shaders/default.frag
assets/Shaders/default.vert
source/LibRender2/BaseRenderer.cs
source/LibRender2/openGL/VertexArrayObject.cs
source/ObjectViewer/NewRendererS.cs
source/ObjectViewer/ProgramS.cs
source/RouteViewer/NewRendererR.cs
source/RouteViewer/ProgramR.cs

Changes:
The color of a face is now calculated as follows (GL3.0 renderer):
* Base color.
* Apply texture.
* Apply lighting result.
* Apply fog.

Fix: Issues with fog / lighting

---

assets/Shaders/default.frag
assets/Shaders/default.vert
source/LibRender2/BaseRenderer.cs
source/LibRender2/Lighting/Lighting.cs
source/LibRender2/Shaders/Shader.cs
source/LibRender2/openGL/ShaderLayout.cs
source/ObjectViewer/NewRendererS.cs
source/ObjectViewer/System/GameWindow.cs
source/OpenBVE/Graphics/NewRenderer.cs
source/OpenBVE/Graphics/Screen.cs
source/OpenBVE/Parsers/Panel/Panel2CfgParser.cs
source/OpenBVE/Parsers/Panel/PanelCfgParser.cs
source/OpenBveApi/Objects/Helpers/MeshBuilder.cs
source/OpenBveApi/Objects/MeshMaterial.Flags.cs
source/OpenBveApi/Objects/MeshMaterial.cs
source/OpenBveApi/OpenBveApi.csproj
source/Plugins/Object.DirectX/Parsers/XObjectParser.cs
source/Plugins/Object.Wavefront/Parsers/WavefrontObjParser.cs
source/RouteViewer/NewRendererR.cs

Fixes issues with GL3.0 lighting being incorrect.
https://github.com/leezer3/OpenBVE/issues/480
Adapted the lighting code in the shader using the following tool:
https://github.com/mojocorp/ShaderGen
Other notes:
We weren't transforming the light position by the current view matrix.

Change: Improve GL3.0 lighting

---

source/LibRender2/BaseRenderer.cs
source/LibRender2/LibRender2.csproj
source/LibRender2/openGL/IndexBufferObject.cs
source/LibRender2/openGL/VertexArrayObject.cs
source/LibRender2/openGL/VertexBufferObject.cs
source/LibRender2/packages.config
source/ObjectViewer/ProgramS.cs
source/ObjectViewer/formOptions.cs

The GC may be executed while releasing resources, and the collection may be changed. (InvalidOperationException)

Fix: issue where collections are modified while releasing resources

---

assets/Shaders/default.frag
assets/Shaders/default.vert
source/LibRender2/Primitives/Cube.cs
source/LibRender2/openGL/VertexArrayObject.cs
source/ObjectViewer/NewRendererS.cs
source/ObjectViewer/ProgramS.cs
source/ObjectViewer/System/GameWindow.cs
source/OpenBveApi/Objects/Helpers/MeshBuilder.cs
source/Plugins/Route.CsvRw/Plugin.cs
source/RouteViewer/ProgramR.cs
source/RouteViewer/System/Gamewindow.cs

https://github.com/leezer3/OpenBVE/commit/82e43116648c53933d8178c0e0a9f9fa793c8048
Reverts this, and hopefully fixes things a little better this time around.
I've also hidden the internal drawing routines for the cube (As we've created a specific class for it, IMHO it should only have the single draw method)
cc @s520

Changes to Vertex Colors & Emissive Hack

---

makefile

Adds a little prequisite checking to our makefile
https://bveworldwide.forumotion.com/t1975-linux-compilation-not-registered-task-move#20024
Might be worth thinking about CAKE or FAKE possibly.
cc @s520

Change: Add some prequisite checking in the makefile

---

azure-pipelines-release.yml
azure-pipelines.yml

This PR fixes the issue where daily build would work triggered by PR.
I thought it wasn't intentional behavior.
If it is intentional behavior, please close this PR.

Fix: the issue where daily build would work triggered by PR

---

azure-pipelines-release.yml
azure-pipelines.yml

This PR fixes the error that occurred at #633.

Fix: the error on Azure Pipelines again

---

source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs
source/OpenBveApi/Objects/ObjectTypes/AnimatedObjectCollection.cs
source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.cs
source/TrainManager/Car/Bogie/Bogie.cs
source/TrainManager/Car/CarBase.cs

This PR removes the duplicate code for reverse function.

Change: Move reverse function to AnimatedObject

---

source/LibRender2/BaseRenderer.cs
source/LibRender2/Shaders/Shader.cs
source/ObjectViewer/Hosts.cs
source/OpenBVE/Graphics/NewRenderer.cs
source/OpenBVE/System/Host.cs
source/OpenBveApi/Math/Vectors/Vector3.cs
source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs
source/OpenBveApi/Objects/ObjectTypes/AnimatedObjectCollection.cs
source/OpenBveApi/Objects/ObjectTypes/AnimatedWorldObject.StateSound.cs
source/OpenBveApi/Objects/ObjectTypes/StaticObject.cs
source/OpenBveApi/Objects/ObjectTypes/UnifiedObject.cs
source/OpenBveApi/Objects/ObjectTypes/WorldSound.cs
source/OpenBveApi/System/Hosts.cs
source/OpenBveApi/World/Transformations.cs
source/Plugins/Route.CsvRw/Structures/Signals/SignalData.BVE4.cs
source/RouteManager2/SignalManager/SignalObject.Animated.cs
source/RouteManager2/SignalManager/SignalObject.Compatability.cs
source/RouteManager2/SignalManager/SignalObject.cs
source/RouteViewer/System/Host.cs

Related: https://github.com/leezer3/OpenBVE/issues/645#issuecomment-867169596

Change: confusing variable names

---

source/OpenBVE/Game/AI/AI.SimpleHuman.cs

https://github.com/leezer3/OpenBVE/issues/702
@MarcRiera 
This I think should solve the issue. Makes the AI a little bouncy on the brakes in this regard (might want a bigger interval, but that would make the speed graph bounce instead), see what you think

Change: Improve the behavior of the AI on a downwards gradient

---

source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs

Accidentally left a debug message in DenshaDeGoInput, sorry!

Remove debug message

---

source/Plugins/Object.Animated/Plugin.Parser.cs

Please merge it. This is the solution of #822 .

Fix: Sounds are now playable in animated collections

---

source/OpenBVE/Graphics/Renderers/Overlays.HUD.cs
source/TrainManager/Handles/Handles.Brake.cs

Some works on #821
This PR *should hopefully* fix the duplicated overlay on the power notch.
(Also fix a crash when the custom notch description is not available for the current notch)

Fix: Notch related issue

---

source/OpenBveApi/Objects/Helpers/MeshBuilder.cs
source/Plugins/Object.CsvB3d/Plugin.Parser.cs

https://bveworldwide.forumotion.com/t2244-abnormal-colorall-behaviour
This PR *should* fix the above issue

Fix: ColorAll not applying to current MeshBuilder

---

source/ObjectViewer/FunctionScripts.cs
source/OpenBVE/Game/ObjectManager/AnimatedObjects/FunctionScripts.cs
source/OpenBVE/System/Input/ProcessControls.Digital.cs
source/OpenBveApi/FunctionScripts/FunctionScript.cs
source/OpenBveApi/FunctionScripts/Instructions.cs
source/OpenBveApi/Interface/Input/Commands.cs
source/Plugins/Train.OpenBve/Sound/SoundCfg.Xml.cs
source/Plugins/Train.OpenBve/Train/BVE/TrainDatParser.cs
source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.CarNode.cs
source/RouteViewer/FunctionScripts.cs
source/TrainManager/Car/CarBase.cs
source/TrainManager/Handles/AbstractHandle.cs
source/TrainManager/Handles/Handles.AirBrake.cs
source/TrainManager/Handles/Handles.Brake.cs
source/TrainManager/Handles/Handles.LocoBrake.cs
source/TrainManager/Handles/Handles.Power.cs
source/TrainManager/SafetySystems/DSD/DriverSupervisionDevice.ResetModes.cs
source/TrainManager/SafetySystems/DSD/DriverSupervisionDevice.TriggerMode.cs
source/TrainManager/SafetySystems/DSD/DriverSupervisionDevice.Types.cs
source/TrainManager/SafetySystems/DSD/DriverSupervisionDevice.cs
source/TrainManager/SafetySystems/Plugin/Plugin.cs
source/TrainManager/Train/TrainBase.cs
source/TrainManager/TrainManager.csproj

This PR aims to implement a DSD device.
Likely to be XML only feature, although could probably be added to train.dat with relatively little pain.
**Available Intervention Modes:**
* Cuts power
* Applies service brakes
* Applies emergency brakes
**Available Reset Modes:**
* Power handle change
* Brake handle change
* Any handle changed
* Independant DSD key press
* Independant DSD key held
**Available Trigger Modes:**
* DSD is always active.
* DSD is active when moving.
* DSD is active when a direction is set or the train is moving.

New: Implement Driver Supervision Device (DSD)

---

source/InputDevicePlugins/DenshaDeGoInput/Controller.Classic.cs
source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs

Densha de GO ghost input fixes

---

source/Plugins/Route.Bve5/MapParser/ConvertComponents.cs

BVE5: Adds interpolation to legacy gradient / curves.
Ref:
https://github.com/leezer3/OpenBVE/issues/1045#issuecomment-2275286076

Change: Interpolation of legacy gradient / curves

---

assets/Languages/zh-HK.xlf

This PR finishes the translation for zh-HK.

Update zh-HK Translation

---

assets/Languages/zh-CN.xlf

This PR made some minor revisions and changes in expression.
I hope don't mind my early additions.
> command, couple_rear: "Coupling the rear cars manually."
> command, couple_front: "Coupling the front cars manually."

Update zh-CN Translation

---

source/OpenBVE/Game/ObjectManager/AnimatedObjects/FunctionScripts.cs
source/OpenBveApi/FunctionScripts/FunctionScript.cs
source/OpenBveApi/FunctionScripts/Instructions.cs
source/Plugins/Route.CsvRw/Namespaces/Track/Track.cs

https://github.com/leezer3/OpenBVE/issues/1140
Need to check whether there are actually any routefiles in my collection using negative limits. This is the biggest concern at the minute.
Documentation should be updated for RouteLimit command too,
Also adds a SectionLimit command, as this seems a logical addition.

Fix RouteLimit issues in scripting

---

source/TrainEditor2/Models/App.cs
source/TrainEditor2/Models/Others/TreeViewItemModel.cs
source/TrainEditor2/Models/Trains/Car.cs
source/TrainEditor2/Models/Trains/ParticleSource.cs
source/TrainEditor2/TrainEditor2.csproj
source/TrainEditor2/ViewModels/AppViewModel.cs
source/TrainEditor2/ViewModels/Trains/CarViewModel.cs
source/TrainEditor2/ViewModels/Trains/ParticleSourceViewModel.cs
source/TrainEditor2/ViewModels/Trains/TrainViewModel.cs
source/TrainEditor2/Views/FormEditor.Designer.cs
source/TrainEditor2/Views/FormEditor.ParticleSource.cs
source/TrainEditor2/Views/FormEditor.ToolTip.cs
source/TrainEditor2/Views/FormEditor.Train.cs
source/TrainEditor2/Views/FormEditor.cs
source/TrainEditor2/Views/FormEditor.resx

This PR implements particle sources into TE2.
Some somewhat nasty bodgery to get it to use the same add / remove buttons as cars, and I'm not exactly fond of some of the Linq queries used.
Partially tested, not fully at the minute.
Need to specifically verify that the GL controls are all still functional- Opening the main form in the WinForms designer breaks these, (Could not find type error, which if we ignore and edit busts things)
Should figure out why this happens and fix it properly.

New: Implement particles into TE2

---

source/OpenBveApi/Objects/ObjectTypes/StaticObject.cs
source/Plugins/Route.CsvRw/CsvRwRouteParser.Preprocess.cs
source/Plugins/Route.CsvRw/DuplicateKeyComparer.cs
source/Plugins/Route.CsvRw/Route.CsvRw.csproj
source/Plugins/Route.CsvRw/Structures/Expression.PositionedExpression.cs
source/Plugins/Route.CsvRw/Structures/Expression.cs

https://bveworldwide.forumotion.com/t2497-long-loading-times#22199
This currently reduces load times on the linked problematic route from 71s to 55s.
It should be possible to use an ordered list throughout the entire route parser, but need to work on this a bit more.

Load Speed Improvements
