openBVE/OpenBve/OldCode/Interface.cs
Previous version works only with the old Security<letter> commands, now it should work with all commands.
=> Fix bug in SecurityToVirtualKey

openBVE/OpenBve/OpenBve.csproj
The OpenTk.dll.config file, which is needed for OpenTK to work properly under Linux was not copied to the target directory.
=> Install a copy of OpenTK.dll.config under Linux

openBVE/OpenBve/System/Functions/FileSystem.cs
This appeared in my ~/.config directory:
```sh
$ find program_title/ OpenBve/
program_title/
program_title/Settings
program_title/Settings/OpenBVE Crash- 2016.3.04[08.14].log
program_title/Settings/logs.bin
program_title/Settings/controls.cfg
program_title/Settings/log.txt
program_title/Settings/OpenBVE Crash- 2016.3.08[13.48].log
program_title/Settings/options.cfg
program_title/ManagedContent
program_title/LegacyContent
program_title/LegacyContent/Railway
program_title/LegacyContent/Railway/Route
program_title/LegacyContent/Train
OpenBve/
OpenBve/Settings
OpenBve/Settings/logs.bin
OpenBve/Settings/controls.cfg
OpenBve/Settings/log.txt
OpenBve/Settings/options.cfg
OpenBve/ManagedContent
OpenBve/LegacyContent
OpenBve/LegacyContent/Railway
OpenBve/LegacyContent/Railway/Route …
```
=> Remove localization from UserData path

openBVE/OpenBve/OldCode/NewCode/GameWindow.cs
How to reproduce bug: throw exception inside LoadEverythingThreaded
What happens during the bug: Loading.Cancel becomes true, LoadingScreenLoop ends, but the window **and it's loop** are still there. Loop is generating ~85% CPU on my dualcore Intel P8600.
What is causing the deadlock: Well, technically, it might not be a deadlock but it looks it is. Draw() is returning immediately because firstFrame is the wrong value because Loading.Complete is false. The CPU load is just Update().
What this fix does: When Loading.Cancel becomes true, LoadingScreenLoops calls Close() on the window. This fixes the deadlock.
PS: do you know where to find trainscript train plugin? OdakyUfan's web is down and google didn't find anything useful at the first glance. Alstom Metropolis requires it and I don't …
=> Fix load error deadlock

openBVE/OpenBve/Game/RouteInfoOverlay.cs, openBVE/OpenBve/System/Functions/Illustrations.cs
- The in-game image of the route map is now cropped removing unused areas at the edges. This reduces, if possible, the portion of screen covered by the map.
- The map image for the main menu is not cropped, though.
In addition:
- For both route map and gradient profile, only the part of route initially considered relevant (from the first to the last station) is scanned and plotted; this ensures padding are (more) respected.
- Factored out a routine used by both images.
- Streamlined a few calculations,
- Added more comments.
Sample screen-shot showing a horizontally cropped map:
=> Crop the in-game route map image to actually used area

RouteViewer/Parsers/CsvRwRouteParser.cs, openBVE/OpenBve/OldParsers/BveRouteParser/CsvRwRouteParser.Structures.cs, openBVE/OpenBve/OldParsers/BveRouteParser/CsvRwRouteParser.cs
Added support in both OpenBVE and RouteViewer for the Cycle.Rail command in CSV routes. It has the same functionality as Cycle.Ground but applied to rail objects. If the Railtype structure index is the same as a Cycle.Rail index, the cycle will be used. If not, it will look for a standard rail object.
More information at #81
=> Cycle.Rail support

ObjectViewer/ObjectManager.cs
If an object had failed to load, no error message was displayed to the user (it was considered that no file was loaded). The error message window is now displayed and ObjectViewer sets the file to 'loaded' (so it can be refreshed too).
=> ObjectViewer error messages fix

.travis.yml, source/OpenBVE/OpenBve.csproj, source/OpenBveApi/OpenBveApi.csproj
I've fixed problems with dependency copying on xbuild, as well as adding travis-ci tests on all platforms using xbuild.
=> Fix Monodevelop on Fresh Build and Add Travis-ci Tests

.gitignore, .travis.yml, makefile
When I was linking people to the daily builds, they often didn't know what to do, as they had never seen .tar.gz before (obviously non-programmers).
I think, while we don't have a automated windows build, we should have the linux build (which works just fine on windows) push a .zip. This way people can just click the zip if they have windows/linux, and the .dmg if they have mac. Obviously the full linux build will be .tar.gz but that can be done easily manually.
**Edit:**  There is a disadvantage however, becasue .zip isn't a solid archive, we go from ~7Mb to ~13Mb
**Edit 2:** We could also do .7z which is familiar and gets us some of the best compression, sitting at 5.9Mb
=> Switch daily builds to use .zip for a wider audience

source/OpenBVE/Game/AI.cs, source/OpenBVE/OldCode/PluginManager.cs, source/OpenBVE/OldCode/TrainManager.cs, source/OpenBVE/Simulation/TrainManager/Doors.cs, source/OpenBVE/Simulation/TrainManager/Station.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBveApi/Runtime.cs
Train plugins can now lock the doors and prevent them from opening or closing. This is done using ElapseData.DoorInterlockState, which can be set to "Unlocked" (normal operation) or "Locked" (the train plugin is blocking the doors).
Trains with automatic doors will open or close them as soon as DoorInterlockState changes to "Unlocked", but won't attempt to close the doors again if the user overrides the system and opens them again (semi-automatic trains). A new boolean in the train's specs called "DoorClosureAttempted" allows OpenBVE to know whether this has happened or not.
=> Door interlocking via train plugin API

source/OpenBVE/OpenBve.csproj
Sorry about not being as active lately, some things came up in my life that kept me away from development for a long while. 
In this interim I installed VS2017RC and I found that the .tt translation commands we had been using weren't working. I did some research and found there is actually a way to have them autotranslate themselves by adding some stuff to the .csproj file. This will allow greater portability as it doesn't tie to any specific version of VS as well as not needing to debug the commands we were using. 
On unix, the .sh file is called as normal. 
Note: S3 is having some problems so Travis-CI is too. I've tested on both windows and linux and this works as expected.
=> Use built in tools for .tt translation instead of custom build step.

makefile
Fixed #150 so that I didn't add LibRender details to makefile. This was caused because I just backported the change without thinking.
=> Fix resources not being linked properly in makefile if project is in subdirectory

documentation/HTML/menu.html, documentation/HTML/route_stationxml.html, source/OpenBVE/Audio/Sounds.cs, source/OpenBVE/Game/AI.cs, source/OpenBVE/Game/Station.cs, source/OpenBVE/OldCode/TrackManager.cs, source/OpenBVE/OldCode/TrainManager.cs, source/OpenBVE/OpenBve.csproj, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Structures.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/Parsers/Script/StationXMLParser.cs
This pull adds a parser, which loads a station's details from an XML file, using the new routefile command stationxml
e.g:
6500, .stationXML ..\includes\Dockyard.xml
```XML
<openBVE>
<Station>
<Name>Dockyard</Name>
<ArrivalTime>12.3130</ArrivalTime>
<DepartureTime>12.3150</DepartureTime>
<Doors>Left</Doors>
<ForcedRedSignal>False</ForcedRedSignal>
<PassengerRatio>10</PassengerRatio>
<RequestStop>
<Probability>50</Probability>
<Distance>700</Distance>
<StopMessage>You will need to stop at Dockyard today.</StopMessage>
<PassMessage>No passengers for Dockyard.</PassMessage>
</RequestStop>
</Station>
</openBVE>
```
All parameters from a standard .sta command are supported.
To set the station type:
```XML
<Type>ChangeEnds</Type>
```
or
```XML
<Type>Terminal</Type>
```
A **Request Stop** may be …
=> Add Station XML parser and Request stops

source/OpenBVE/OpenBve.csproj, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ObjectDictionary.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Structures.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/RouteViewer/Parsers/CsvRwRouteParser.cs
Closes https://github.com/leezer3/OpenBVE/issues/185
Needs some more testing to make sure nothing has broken.
* ~~Test what happens when an object indices is declared twice.~~ ==> Broken, see below.
* Double-check routes using _.Crack_ and the other deformable object types.
* ~~Do we port to Route Viewer? https://github.com/leezer3/OpenBVE/pull/165 may negate the need for this, but not sure how far away that is.~~
=> Change: Improve handling of excessively large StructureIdx values

source/ObjectViewer/ObjectManager.cs, source/ObjectViewer/ObjectViewer.csproj, source/ObjectViewer/Parsers/WavefrontObjParser.cs, source/ObjectViewer/WorldS.cs, source/OpenBVE/Game/ObjectManager/ObjectManager.LoadObject.cs, source/OpenBVE/OldCode/World.cs, source/OpenBVE/OpenBve.csproj, source/OpenBVE/Parsers/Object/Generic/WavefrontObjParser.cs, source/RouteViewer/ObjectManager.cs, source/RouteViewer/Parsers/WavefrontObjParser.cs, source/RouteViewer/RouteViewer.csproj, source/RouteViewer/WorldR.cs
This adds a parser for Wavefront .obj files to openBVE.
**Limitations:**
- Smoothing groups are not implemented.
- Ambient and diffuse materials are both just hooked into the main texture, as opposed to being separate.
- Specular maps not supported.
- Bump maps not supported.
- Emissive color not yet supported. (I need to find some stuff using emission and test it so I can get the half-distance equation correct)
- Lighting mode not supported.
=> Wavefront obj

source/ObjectBender/ObjectBender.csproj, source/ObjectViewer/ObjectViewer.csproj, source/OpenBVE/Audio/Sounds.SoundBuffer.cs, source/OpenBVE/Audio/Sounds.SoundSource.cs, source/OpenBVE/Audio/Sounds.Update.cs, source/OpenBVE/Audio/Sounds.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/AnimatedObject.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/AnimatedObjectCollection.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/AnimatedWorldObject.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/TrackFollowingObject.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/WorldSound.cs, source/OpenBVE/Game/ObjectManager/ObjectManager.cs, source/OpenBVE/Game/ObjectManager/WorldObject.cs, source/OpenBVE/OpenBve.csproj, source/OpenBVE/Parsers/Object/BVE/AnimatedObjectParser.cs, source/OpenBVE/Simulation/TrainManager/Functions.cs, source/OpenBVE/Simulation/TrainManager/Train/BrakeSystem.cs, source/OpenBveApi/OpenBveApi.csproj, source/Plugins/OpenBveAts/OpenBveAts.csproj, source/Plugins/Sound.Flac/Sound.Flac.csproj, source/Plugins/Sound.RiffWave/Sound.RiffWave.csproj, source/Plugins/Texture.Ace/Texture.Ace.csproj, source/Plugins/Texture.BmpGifJpegPngTiff/Texture.BmpGifJpegPngTiff.csproj
This branch has the initial work for attaching sounds to a Track Following animated object.
Sample animated file to start with:
```
[Object]
position = -4,0,0
States = 16xx.b3d
TrackFollowerFunction = if[value == 0, value + 1000, if[trackdistance > -200,if[value < 0, value, value - 10 * delta], value]]
Sound=Steamer.wav
```
The sound for this is played looped at a constant 100% volume & pitch when the object is visible (Stopped if the state is -1), emanating from the object's front axle.
The sound radii at present is a constant 30m (As per other trains within the simulation), but before merging, this should be changed to allow the user to set the radii appropriately.
Bugs:
* ~~Something not quite right with the sound attachments at the minute, occasionally managing to get the wrong type …
=> New: Sounds can be attached to a TrackFollower

documentation/HTML/route_csv.html, source/ObjectViewer/FunctionScripts.cs, source/ObjectViewer/TrainManagerS.cs, source/OpenBVE/Game/Events/EventTypes/DestinationChange.cs, source/OpenBVE/Game/Game.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/FunctionScripts.cs, source/OpenBVE/OpenBve.csproj, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.RouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.SignalData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Structures.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/Simulation/TrainManager/Train/Train.cs, source/OpenBVE/System/Loading.cs, source/OpenBVE/System/Plugins/PluginManager.cs, source/OpenBveApi/Runtime.cs, source/RouteViewer/FunctionScripts.cs, source/RouteViewer/TrainManagerR.cs
This PR implements destinations for trains.
Train.Destination(__InitialDestination__) 
__InitialDestination__ should be an integer, representing the initial destination displayed by the train at the first stop
---
Track.Destination(__Type__ , __BeaconStructureIndex__ , __NextDestination__ , __PreviousDestination__ , __TriggerOnce__ , __X__ , __Y__ , __Yaw__ , __Pitch__ , __Roll__)
__Type__ should be one of the following: _-1_ : AI trains only _0_ : All trains _1_ : Player train only
__BeaconStructureIndex__ should be the index of any beacon object previously declared, or -1 to show no visible marker.
__NextDestination__ represents the destination to change to when passing over this beacon forwards, or _-1_ to not change.
__PreviousDestination__ represents the destination to change to when …
=> Destination event

source/OpenBVE/Simulation/TrainManager/Car/ConstantSpeedDevice.cs
This PR fixes problems that ConstantSpeed device doesn't work, which occurs after 1.5.2.3.
=> Fix: Issue that ConstantSpeed Device doesn't work

source/OpenBVE/System/GameWindow.cs
This PR fixes problems that plugin doesn't be unloaded when OpenBVEGame window is closed.
=> Fix: Issue that plugin doesn't be unloaded when OpenBVEGame window is closed

source/ObjectViewer/ObjectViewer.csproj, source/OpenBVE/OpenBve.csproj, source/OpenBveApi/OpenBveApi.csproj, source/Plugins/OpenBveAts/Train.cs, source/RouteViewer/RouteViewer.csproj
This PR fix build error and reference error.
- build error due to VS2013 (also Mono 3.2.8) not supporting get-only property
- reference error due to a typo in HintPath on monodevelop
=> Fix: Build error and reference error

source/OpenBVE/Game/Menu.cs, source/OpenBVE/System/GameWindow.cs, source/OpenBVE/System/MainLoop.cs, source/OpenBVE/UserInterface/formMain.Designer.cs, source/OpenBVE/UserInterface/formMain.Start.cs, source/OpenBVE/UserInterface/formMain.cs
Even in our environment, the same problem as #213 is occurring.
This PR has made minor modifications to #214.
With this fix, mono has been correctly terminated in our environment.
Our environment is as follows.
- fedora 28 with mono 5.16.0.187
- Ubuntu 16.04.5 LTS with mono 5.14.0.177
=> Fix: Issue that GameWindow doesn't close under mono

source/OpenBVE/System/Input/JoystickManager.cs
This PR fix issue that joystick is not automatically recognized on Linux.
I think that it is meaningless to check the value of IsConnected on Linux.
The reason is because there is the following comment to the [source code of OpenTK](https://github.com/opentk/opentk/blob/e911f0b7698e7bc32fa1c4eab37f9e50f7bd92a3/src/OpenTK/Platform/Linux/LinuxJoystick.cs#L413).
> Only mark the joystick as connected when we actually start receiving events.
Otherwise, the Xbox wireless receiver will register 4 joysticks even if no actual joystick is connected to the receiver.
Since the current program checks the value of IsConnected, OpenBVE will not be recognized unless some operation is done with the joystick.
=> Fix: Issue that joystick is not automatically recognized on Linux

assets/Controls/Default keyboard assignment.controls, source/OpenBVE/Audio/Sounds.SoundSource.cs, source/OpenBVE/Audio/Sounds.Update.cs, source/OpenBVE/Audio/Sounds.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Structures.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBveApi/Interface/Input/Commands.CommandInfo.cs, source/OpenBveApi/Interface/Input/Commands.cs
This PR adds the syntax called Track.MicSound that plays the sound from the microphone on the simulation.
The usage of this syntax is as follows.
`Track.MicSound(X, Y, BackwardTolerance; ForwardTolerance)`
Specify the range to be played by BackwardTolerance and ForwardTolerance.
The PLAY_MIC_SOUNDS command toggles playback on and off.
The PLAY_MIC_SOUNDS command is assigned to W key by default.
=> New: Add microphone input

source/InputDevicePlugins/SanYingInput/SanYingInput.cs
This PR fix problem between P1 and P2 at OHC-PC01.
P5 may be output when the notch is between P1 and P2.
This is an unintended output and should be excluded.
This problem is due to OHC-PC01, it must be corrected by the input device plugins.
=> Fix: problem between P1 and P2 at OHC-PC01

source/OpenBVE/Graphics/Fonts.cs
This PR fix crash when loading.
Occasionally, OpenBVE will abnormally terminate with the following crash log when loading.
[OpenBVE Crash- 2019.2.28[08.08].log](https://github.com/leezer3/OpenBVE/files/2912696/OpenBVE.Crash-.2019.2.28.08.08.log)
When I debug, the program stops with the following code.
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/System/Functions/Illustrations.cs#L303
I thought that GDI+ is not thread-safe and that problems have occurred with other Draw-like functions that are not locked.
When I locked the following function it no longer crashes.
https://github.com/leezer3/OpenBVE/blob/master/source/OpenBVE/Graphics/Fonts.cs#L45
This function is called during loading.
=> Fix: crash when loading

source/LibRender/LibRender.csproj, source/LibRender/Overlays/Keys.cs, source/LibRender/Primitives/Cube.cs, source/LibRender/Primitives/Rectangle.cs, source/LibRender/Renderer.cs, source/ObjectViewer/ProgramS.cs, source/ObjectViewer/RendererS.cs, source/OpenBVE/Graphics/Renderer/Events.cs, source/RouteViewer/ProgramR.cs, source/RouteViewer/RendererR.cs
Follows up to #351 .  #350 & #276 
This moves the following to the shared renderer:
* Cube drawing (Used for the Object Viewer co-ordinate display & event overlays in the main program / viewers)
* Key overlay drawing
=> Shared Renderer, Part 3

.travis.yml, DebianControl.sh
Stretch is now Debian OldStable, and this gives us a much newer Mono version to play with!
This *should* be seamless hopefully.
Whilst we don't actually require anything newer than 3.2.8 at the minute, this should let us use a few newer features if we need.
=> Change: Bump required Mono version

source/OpenBVE/Game/AI/AI.SimpleHuman.cs, source/OpenBVE/Game/Game.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/TrackFollowingObject.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/WorldSound.cs, source/OpenBVE/Game/PointsOfInterest.cs, source/OpenBVE/Game/Timetable.cs, source/OpenBVE/Game/TrackManager/TrackManager.TrackFollower.cs, source/OpenBVE/Game/TrackManager/TrackManager.cs, source/OpenBVE/Graphics/Renderer/Events.cs, source/OpenBVE/OldCode/TrainManager.cs, source/OpenBVE/OldCode/World.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/Simulation/TrainManager/Car/Car.Bogie.cs, source/OpenBVE/Simulation/TrainManager/Car/Car.cs, source/OpenBVE/System/Functions/Illustrations.cs, source/OpenBVE/System/GameWindow.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBVE/System/MainLoop.cs, source/RouteManager/CurrentRoute.cs, source/RouteViewer/GameR.cs, source/RouteViewer/LoadingR.cs, source/RouteViewer/Parsers/CsvRwRouteParser.cs, source/RouteViewer/ProgramR.cs, source/RouteViewer/RendererR.cs, source/RouteViewer/TrackManagerR.cs, source/RouteViewer/WorldR.cs
Marginal bit of refactoring work in the TrackFollower class.
This makes it so that it will take either an absolute track position (Moves the follower to said position, was the previous behaviour), or a relative position. 
* A lot less passing around of relative positions.
* Moves the static methods used to update the track follower in Route Viewer into methods pertaining to the follower as per the main program.
* Only relative in the main program.
* A bunch of stuff probably should use this (e.g. some of the camera based stuff), but doesn't for legacy reasons.
* Test and check that nothing has gone awry.
* Make RouteViewer use the multiple track logic from https://github.com/leezer3/OpenBVE/pull/326
=> Refactor TrackFollower to take an absolute or a relative position

UploadScript.sh
This PR fix an issue that Linux builds not uploading after Mono bump.
=> Fix: Linux builds not uploading after Mono bump

source/TrainEditor2/App.config, source/TrainEditor2/IO/Sounds/Xml/Parser.cs, source/TrainEditor2/IO/Trains/TrainDat/Parser.cs, source/TrainEditor2/Models/App.cs, source/TrainEditor2/Models/Trains/Motor.Functions.cs, source/TrainEditor2/Models/Trains/Motor.Simulation.cs, source/TrainEditor2/Models/Trains/Motor.cs, source/TrainEditor2/Program.cs, source/TrainEditor2/Systems/Fonts.cs, source/TrainEditor2/Systems/Host.cs, source/TrainEditor2/TrainEditor2.csproj, source/TrainEditor2/ViewModels/Trains/MotorViewModel.cs, source/TrainEditor2/ViewModels/Trains/TrainViewModel.cs, source/TrainEditor2/Views/FormDelay.cs, source/TrainEditor2/Views/FormEditor.Acceleration.cs, source/TrainEditor2/Views/FormEditor.Car.cs, source/TrainEditor2/Views/FormEditor.Designer.cs, source/TrainEditor2/Views/FormEditor.Functions.cs, source/TrainEditor2/Views/FormEditor.Motor.cs, source/TrainEditor2/Views/FormEditor.Panel.cs, source/TrainEditor2/Views/FormEditor.Sound.cs, source/TrainEditor2/Views/FormEditor.Train.cs, source/TrainEditor2/Views/FormEditor.cs, source/TrainEditor2/Views/FormEditor.resx, source/TrainEditor2/packages.config
This PR fix a crash in the motor sound simulation.
However, the numerical value of the scale of the Motor sound settings graph is no longer displayed.
This is because I decided to use OpenGL.
Can I use the main program or viewer text display mechanism?
I am worried about this.
What do you think?
Related to #388 .
=> Fix: a crash in the motor sound simulation

assets/Shaders/default.vert, source/LibRender2/Primitives/Cube.cs, source/LibRender2/openGL/IndexBufferObject.cs, source/LibRender2/openGL/VertexArrayObject.cs, source/LibRender2/openGL/VertexBufferObject.cs, source/ObjectViewer/NewRendererS.cs, source/OpenBveApi/Math/Matrix4.cs, source/OpenBveApi/Math/Quaternion.cs, source/OpenBveApi/Math/Vectors/Vector3.cs, source/OpenBveApi/Objects/ObjectTypes/StaticObject.cs
Some more shader improvements. (The last got merged due to the missing animated object part bug being critical)
* openTK notice added to matrix & quaternion code (Missed this from the last one....)
* The Z-axis flip is now performed inside the shader- This allows an implicit operator when passing the vertex co-ordinates, which is much neater (and makes it so much simpler to debug...)
* The vertex indices are stored as ushort as opposed to int. This does limit us to 65,535 verts per VBO, but frankly something else will fall over long before we hit this limit. On the flip side, it saves us 2 bytes per vertex. This is likely to be of use on systems with lower memory bandwidth, which are also most likely to benefit from the VBO changes.
Work in progress again.
I suspect the VBO creation can …
=> Shader improvements, Part 2

source/OpenBVE/Simulation/TrainManager/Car/Car.cs
This PR fix the issue that the screen cannot be changed by touch. (#411)
If you give true to the initialization function of the CarSection class, objects that should be hidden will also be displayed by the initialization function of the AnimatedObject class.
=> Fix: the issue that the screen cannot be changed by touch

source/OpenBVE/Graphics/Renderers/Touch.cs, source/OpenBVE/Parsers/Panel/Panel2CfgParser.cs, source/OpenBVE/Parsers/Panel/PanelAnimatedXmlParser.cs, source/OpenBVE/Parsers/Panel/PanelXmlParser.cs, source/OpenBVE/Simulation/TrainManager/Car/Car.CarSection.cs, source/TrainEditor2/IO/IntermediateFile/Parser.cs, source/TrainEditor2/IO/IntermediateFile/Writer.cs, source/TrainEditor2/IO/Panels/Bve4/Writer.cs, source/TrainEditor2/IO/Panels/Xml/Parser.cs, source/TrainEditor2/IO/Panels/Xml/Writer.cs, source/TrainEditor2/Models/App.cs, source/TrainEditor2/Models/Panels/Panel.cs, source/TrainEditor2/Models/Panels/TouchElement.cs, source/TrainEditor2/Models/Sounds/Sound.cs, source/TrainEditor2/TrainEditor2.csproj, source/TrainEditor2/ViewModels/Panels/ThisViewModel.cs, source/TrainEditor2/ViewModels/Panels/TouchElementViewModel.cs, source/TrainEditor2/Views/FormEditor.Designer.cs, source/TrainEditor2/Views/FormEditor.Functions.cs, source/TrainEditor2/Views/FormEditor.Panel.cs, source/TrainEditor2/Views/FormEditor.Sound.cs, source/TrainEditor2/Views/FormEditor.Touch.cs, source/TrainEditor2/Views/FormEditor.cs, source/TrainEditor2/Views/FormTouch.Designer.cs, source/TrainEditor2/Views/FormTouch.cs, source/TrainEditor2/Views/FormTouch.resx
This PR add multiple sounds and commands to one touch element on the panel.
Use the following format:
```
<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<openBVE xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
<Panel>
<Screen>
<Touch>
<SoundEntries>
<Entry>
<Index>-1</Index>
</Entry>
</SoundEntries>
<CommandEntries>
<Entry>
<Name>N/A</Name>
<Option>0</Option>
</Entry>
</CommandEntries>
</Touch>
</Screen>
</Panel>
</openBVE>
```
In addition, several bugs in TrainEditor2 were fixed.
=> Add: multiple sounds and commands to one touch element on the panel

source/OpenBVE/Parsers/Panel/Panel2CfgParser.cs, source/OpenBVE/Parsers/Panel/PanelXmlParser.cs
This PR fix some issues with LinearGauge.  (#421)
- Minimum property do not work properly
- Problem when specifying a time subject
```
[LinearGauge]
Subject = sec
Location = 493, 513
Minimum = 30
Maximum = 59
DaytimeImage = needle2.png
NighttimeImage = needle2.png
TransparentColor = #0000FF
Width = 32
Layer = 10
```
Additionally, "Needle" angles in Panel.xml were not being converted to radians.
=> Fix: some issues with LinearGauge

source/ObjectViewer/Hosts.cs, source/OpenBVE/Game/Game.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.RouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Structures.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/System/Host.cs, source/OpenBveApi/Routes/Track.TrackFollower.cs, source/OpenBveApi/System/Hosts.cs, source/RouteManager2/CurrentRoute.cs, source/RouteViewer/GameR.cs, source/RouteViewer/Parsers/CsvRwRouteParser.cs, source/RouteViewer/System/Host.cs
This changes rails to use a dictionary type accessor, as opposed to a single array.
This drastically reduces memory usage in the route parser and sim where an author has used mega high rail numbers.
* ~~Curve calculation for trains running on secondary tracks seems broken. (Probably using a for loop somewhere we shouldn't now...)~~ Fixed.
* ~~Not implemented in Route Viewer / Object Viewer, these are broken in this PR at the minute.~~ Route Viewer doesn't implement the parser changes, but implements the backend changes. Should be enough, and hopefully will move the route loading code to a plugin soon.
cc @s520 - Multiple rail running is primarily your code.
=> Change: Shift rails to a dictionary accessor.

documentation/HTML/object_animated.html
This PR cleans up some of the Function Script documentation that I wrote to be more clear and correct. It also clarifies that all infix operators in function scripts are right-to-left except the addition/subtraction and equality operators. I also added examples so it should be easier for people to understand.
Rendered:
In other news I am still alive and around :)
=> Fix Function Script Documentation and Clarify Infix Operator Associativity

source/LibRender2/Backgrounds/Background.cs, source/LibRender2/BaseRenderer.cs, source/LibRender2/Objects/ObjectLibrary.cs, source/LibRender2/Primitives/Cube.cs, source/ObjectViewer/NewRendererS.cs, source/OpenBVE/Graphics/NewRenderer.cs, source/OpenBVE/Graphics/Renderers/Overlays.Debug.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBVE/System/MainLoop.cs, source/RouteViewer/NewRendererR.cs
#433 fix was flawed.
This PR re-correct it.
This fix prevents switching to a new renderer if the creation of the default shader fails.
=> Fix: the issue that an exception occurred in legacy OpenGL (again...)

source/ObjectViewer/Hosts.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.Preprocess.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.PreprocessOptions.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/Parsers/Train/ExtensionsCfgParser.cs, source/OpenBVE/System/Host.cs, source/OpenBVE/System/Program/CommandLine.cs, source/OpenBVE/UserInterface/formMain.Start.cs, source/OpenBVE/UserInterface/formMain.cs, source/OpenBveApi/Objects/ObjectInterface.cs, source/OpenBveApi/System/Hosts.cs, source/OpenBveApi/System/TextEncoding.cs, source/Plugins/Object.Animated/Plugin.cs, source/Plugins/Object.CsvB3d/Plugin.cs, source/Plugins/Object.DirectX/Plugin.cs, source/Plugins/Object.LokSim/Plugin.cs, source/Plugins/Object.Msts/Plugin.cs, source/Plugins/Object.Wavefront/Plugin.cs, source/RouteViewer/Parsers/CsvRwRouteParser.cs, source/RouteViewer/System/Host.cs
This PR contains the following changes in addition to the title.
- Move: the function that determines the extension of the object file to the API
- Fix: the range of $Char and $CharAscii argument
- Fix: typo in CsvRwRouteParser.PreprocessOptions.cs
=> Change: use API functions to determine encoding

source/OpenBVE/Game/AI/AI.TrackFollowingObject.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.ApplyRouteData.cs, source/OpenBVE/Parsers/Route/BVE/CsvRwRouteParser.cs, source/OpenBVE/Parsers/Script/TrackFollowingObjectParser.cs, source/OpenBveApi/Routes/Track.TrackElement.cs, source/OpenBveApi/Routes/Track.TrackFollower.cs
If you specify the deceleration or acceleration as shown below, TFO will stop for a moment.
```xml
<Stop>
<Decelerate>1.62</Decelerate>
<StopPosition>400</StopPosition>
<StopTime>00.0000</StopTime>
<Accelerate>0</Accelerate>
<TargetSpeed>60</TargetSpeed>
<Direction>1</Direction>
<Rail>2</Rail>
</Stop>
```
I made the following changes to fix this problem.
- Add `<Point>`
This element can specify the passing speed of the point.
However, it has no stop-related elements. (`<Doors>`, `<StopTime>`, `<Direction>`)
```xml
<Point>
<Decelerate>1.62</Decelerate>
<Position>400</Position>
<PassingSpeed>60</PassingSpeed>
<Accelerate>0</Accelerate>
<TargetSpeed>60</TargetSpeed>
<Rail>2</Rail>
</Point>
```
- Add `<Points>` to `<Stops>` aliases.
- Add `<Position>` to `<StopPosition>` aliases.
Also, the …
=> Fix: issues with changing speed and rail index while driving at TFO

Building.md
This PR update Building.md.
- If NuGet version is lower than 2.16, package restore fails.
- Build fails when using Mono package from distribution.
- On Fedora I have confirmed that the same version also fails. We need to see what happens in Debian.
- Ubuntu on Travis seems to get Mono from the Mono project repository.
Related: https://bveworldwide.forumotion.com/t1890-missing-files-in-compilation-of-source-in-linux-not-debian
=> Update: Building.md [ci skip]

source/OpenBVE/Graphics/Renderers/Touch.cs, source/OpenBVE/Simulation/TrainManager/Car/Car.cs
This PR fix a crash of trains using digital gauges in legacy OpenGL.
Related: #437
=> Fix: a crash of trains using digital gauges in legacy OpenGL

source/LibRender2/Text/OpenGlFont.cs, source/LibRender2/Text/OpenGlFontTable.cs
This PR fix missing characters of OpenGlFont.
Related: #473
First, take a look at the screenshot below.
At first glance, it looks normal, but "ー" in "メインメニュー is missing.
"ー" is U+30FC.
Next, look at the image that outputs the Bitmap of OpenGlFontTable.
This image must contain the letters U+3000 to U+30FF.
But U+30F7 and later are missing.
Therefore "ー" is not displayed.
Finally, take a look at the OpenGlFontTable after applying this PR.
All letters are drawn correctly.
=> Fix: missing characters of OpenGlFont

source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs
This PR fix an issue where the texture matrix is initialized without using the last value.
=> Fix: an issue where the texture matrix is initialized without using the last value

source/OpenBVE/Game/AI/AI.SimpleHuman.cs, source/OpenBVE/Simulation/TrainManager/Doors.cs, source/OpenBVE/Simulation/TrainManager/Station.cs, source/OpenBVE/System/Input/ProcessControls.cs
This pull request solves the following issues:
1. The checks related to door interlocking were scattered in the code for user input, AI and stations. They are now part of TrainManager.
2. The AI would only open the doors if both sides were unlocked. If a plugin restricted the doors to only one side, the AI would not even try to open the doors and wait indefinitely.
3. At stations where doors should be opened on both sides, boarding does not start until both sides are open. The AI now keeps trying to open all doors in this situation even if one side is already open, in case partial door interlocking was applied initially, to avoid the AI from waiting indefinitely doing nothing.
By the way, the AI currently does not notify plugins about the recently added door virtual keys. Given that the …
=> Move door interlock restrictions to TrainManager and fix related AI behaviour

source/Plugins/Texture.Tga/Texture.Tga.csproj
At
https://www.mono-project.com/download/stable/#download-lin-ubuntu
This installed filename at Ubuntu is
/usr/lib/mono/msbuild/15.0/bin/Microsoft.CSharp.targets
So, compile error causes.
=> Fix:compile error with mono-complete package

source/Plugins/Sound.RiffWave/Plugin.Parser.cs
This PR fix error on files with incorrect cbSize.
Related) https://bveworldwide.forumotion.com/t1939-door-sounds-not-being-played
=> Fix: error on files with incorrect cbSize

source/LibRender2/BaseRenderer.cs, source/LibRender2/LibRender2.csproj, source/LibRender2/Shaders/Shader.cs, source/LibRender2/openGL/IndexBufferObject.cs, source/LibRender2/openGL/VertexArrayObject.cs, source/LibRender2/openGL/VertexBufferObject.cs, source/LibRender2/packages.config, source/ObjectViewer/NewRendererS.cs, source/ObjectViewer/ProgramS.cs, source/ObjectViewer/System/GameWindow.cs, source/ObjectViewer/formOptions.cs, source/OpenBVE/Graphics/NewRenderer.cs, source/OpenBVE/System/GameWindow.cs, source/RouteViewer/NewRendererR.cs, source/RouteViewer/ProgramR.cs, source/RouteViewer/System/Gamewindow.cs, source/TrainEditor2/Views/FormEditor.cs
This takes a different approach entirely to https://github.com/leezer3/OpenBVE/pull/508
If the resources have not explicitly been released, the destructor now enqueues them to be deleted in the next render pass thread.
Appears to solve things properly.
cc @s520 @LabRatAndy
=> Change: Different approach to memory leak with VAOs

source/LibRender2/Primitives/Cube.cs
ObjectViewer crashes due to matrix stack overflow when switching renderers with axes still visible.
=> Fix: matrix stack overflow

source/LibRender2/BaseRenderer.cs, source/OpenBveApi/Objects/Glow.cs, source/OpenBveApi/Objects/Helpers/Material.cs, source/OpenBveApi/Objects/Helpers/MeshBuilder.cs, source/OpenBveApi/Objects/MeshMaterial.Flags.cs, source/OpenBveApi/Objects/MeshMaterial.cs, source/Plugins/Object.CsvB3d/Plugin.Parser.cs, source/Plugins/Object.DirectX/Parsers/AssimpXParser.cs, source/Plugins/Object.DirectX/Parsers/NewXParser.cs, source/Plugins/Object.LokSim/ObjectParser.cs, source/Plugins/Object.Wavefront/Parsers/AssimpObjParser.cs, source/Plugins/Object.Wavefront/Parsers/WavefrontObjParser.cs
Slightly improved version of https://github.com/leezer3/OpenBVE/pull/518
This moves the CrossFadeTexture bool to the MaterialFlags enum, and uses the same enum in the parsers, as opposed to a bunch of bools which then set the flags.
Not done any major testing, but appears to work
cc @s520
=> Crossfading improvements

source/LibRender2/BaseRenderer.cs, source/OpenBveApi/Objects/Glow.cs, source/OpenBveApi/Objects/Helpers/Material.cs, source/OpenBveApi/Objects/Helpers/MeshBuilder.cs, source/OpenBveApi/Objects/MeshMaterial.cs, source/Plugins/Object.CsvB3d/Plugin.Parser.cs
This PR adds cross-fading mode to CSV objects.
Cross-fading mode changes the transparency of DaytimeTexture as opposed to the transparency of NighttimeTexture.
This behavior is different from the conventional one, so it is disabled by default and can be enabled by command.
The command format is as follows:
`EnableCrossfading, value` (value: true or false)
Closed #425
=> Add: cross-fading to switch between day and night textures

source/LibRender2/BaseRenderer.cs, source/OpenBVE/Parsers/Panel/Panel2CfgParser.cs, source/OpenBveApi/Objects/Helpers/MeshBuilder.cs
In BVE4 and 5, panel elements with NighttimeImage defined are rendered with lighting disabled. (#498)
Currently, it is not possible to specify an emissive color for the panel, so the author cannot substitute this effect.
If we want to address this issue like that of a CSV object, we should add an emissive color setting.
However, this effect is the same from BVE4, so I don't think it needs to be changed.
=> Fix: issue where panel elements with NighttimeImage defined are rendered with lighting enabled

assets/Shaders/default.frag, assets/Shaders/default.vert
If you combine textures with emission colors, the new renderer will make the colors brighter.
- Old renderer
- New renderer (Emissive branch #525)
- New renderer (This PR)
I also removed and cleaned up unused variables in the shader.
=> Fix: emissive hack

source/Plugins/Object.CsvB3d/Plugin.Parser.cs
When enabling emissive, the material was flagged as transparent color.
Related: #533
=> Fix: an issue with unwanted material flags being set

.travis.yml, appveyor.yml
This is intended to mirror all new builds so that we get the compiled binary artifacts in Github releases.
Needs mirroring to AppVeyor to produce the installer artifact, which since this has hopefully been fixed will think about later.
Minor wondering if we can get the entire site updated automatically by script (as per the translation bot)
https://docs.travis-ci.com/user/deployment/releases/
Not sure we can automatically link to the latest with the current file naming schema, as this would require the same filename:
https://docs.travis-ci.com/user/deployment/releases/
cc @s520
=> Change: Deploy new release builds to Github also [ci skip]

.travis.yml
Travis CI will only use the last one if there are multiple "deploy" definitions.
https://travis-ci.com/github/leezer3/OpenBVE/builds/187190568/config
In addition, `make debian` only needs to run in one configuration with tagged commits, so I changed it to a single configuration.
This configuration is skipped if the commit is untagged.
Also, building on macOS may take a long time to install sshpass and may time out.
I aim to avoid timeouts using Homebrew's built-in features in Travis CI.
When I tested it several times, there were some cases where it took a long time, but there was no timeout.
=> Fix: .travis.yml

OpenBVE.sln, assets/Languages/en-US.xlf, source/InputDevicePlugins/DenshaDeGoInput/Config.Designer.cs, source/InputDevicePlugins/DenshaDeGoInput/Config.cs, source/InputDevicePlugins/DenshaDeGoInput/Config.resx, source/InputDevicePlugins/DenshaDeGoInput/ControllerClassic.cs, source/InputDevicePlugins/DenshaDeGoInput/ControllerUnbalance.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.csproj, source/InputDevicePlugins/DenshaDeGoInput/InputTranslator.cs, source/InputDevicePlugins/DenshaDeGoInput/OpenTK.dll.config, source/InputDevicePlugins/DenshaDeGoInput/PSController.cs, source/InputDevicePlugins/DenshaDeGoInput/Properties/AssemblyInfo.cs, source/InputDevicePlugins/DenshaDeGoInput/app.config, source/InputDevicePlugins/DenshaDeGoInput/packages.config, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBVE/System/Loading.cs
This pull request implements an input device plugin for Densha de GO! controllers, as mentioned in #528. Technical documentation on the controllers can be found [here](https://gist.github.com/MarcRiera/075b5651039942b2380dc51f0ec1cbc9).
* Compatible with classic (non-USB) Densha de GO! controllers for consoles: Nintendo 64 (TCPP-20003), Sega Dreamcast (TCPP-20003), Sega Saturn (TC-5175290) and Sony PlayStation (SCPH-00051, TCPP-20001, TCPP-20002, TCPP-20008). Naturally, **a USB adapter is required**.
* Initial (untested) compatibility with DGOC-44U and DGC-255 (USB controllers by Unbalance).
* Automatic calibration via a wizard. The user is asked to follow a sequence of button presses and the plugin automatically detects the configuration for the adapter. This only needs to be done once …
=> Densha de GO! controller plugin

assets/Languages/en-US.xlf, source/InputDevicePlugins/DenshaDeGoInput/Config.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/InputTranslator.cs
The Densha de GO! input plugin now uses and stores GUIDs to identify controllers instead of raw indices, which may change after disconnecting and reconnecting a controller.
May be further simplified in the future if it becomes possible to poll devices directly by GUID instead of index. For the time being, it works and should allow disconnecting and reconnecting controllers safely.
=> Use GUIDs for Densha de GO! controllers

.gitignore, .travis.yml, makefile
https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing
We'll hit this whenever it comes in....
Can probably get away with running only the upload build on OS-X as the testing itself will be done on Linux.
Possible alternatives to investigate:
* CircleCI
* Github Actions
Other potential changes to make:
* Cut back further on builds triggered. We can probably loose the makefile test builds (as the publish builds are roughly equivialant)
* Chase Travis for OSS credits. Very unclear as to how this will actually work in practice.
---
As a rough rule of thumb, let's assume 1 commit per day (averaged out including PR builds etc).
It's unclear as to what exactly they're going to charge for, as 90% of the build time is setup of their image (not our code running)
A typical build takes anywhere …
=> Change: Alter travis file [ci skip]

source/OpenBveApi/Objects/ObjectTypes/AnimatedWorldObject.StateSound.cs
This PR fix #578.
PlayOnShow and PlayOnHide are ignored when using multiple buffers, right?
Please point out if they are not ignored.
=> Fix: the shift of buffer index in StateChangeSound

source/SoundManager/Sounds.cs
This PR fix the crash on hardware where the audio capture device does not exist.
This crash occurs when playing a route that contains `Track.MicSound` if it is not physically exist or is disabled.
=> Fix: the crash on hardware where the audio capture device does not exist

source/OpenBVE/Parsers/Script/TrackFollowingObjectParser.cs, source/OpenBveApi/Routes/Track.TrackFollower.cs, source/Plugins/Train.OpenBve/Plugin.cs, source/Plugins/Train.OpenBve/Train/TrainDatParser.cs, source/Plugins/Train.OpenBve/Train/TrainDatparser.Formats.cs, source/TrainManager/TrackFollowingObject/AI/TrackFollowingObject.AI.cs, source/TrainManager/TrackFollowingObject/AI/TravelPointData.cs, source/TrainManager/TrackFollowingObject/TrackFollowingObject.cs
This PR fixes multiple issues with TFO.
- Change: the TFO operation plan to be calculated only when reading the route
- Previously, if the player jumped between stations, it would be calculated again.
- Fix: the method of calculating the acceleration of TFO
- Calculation formula of acceleration was incorrect. (Fix: #608)
I'm currently working on fixing #598.
**UPDATE: 2021/04/21**
- Fix: TrackFollower did not consider the Invalid TrackElement when moving backwards
- Changed to take this into consideration when moving backward as well as when moving forward. (Fix: #598)
=> Fix: multiple issues with TFO

source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/OpenBveApi/Interface/Input/InputDevice.cs, source/TrainManager/SafetySystems/Plugin/Plugin.cs, source/TrainManager/Train/Doors.cs
This PR implements DoorState, SetSignal and SetBeacon for input device plugins, making the data available to them on-par with train plugins.
=> Implement DoorState, SetSignal and SetBeacon for input device plugins

source/AssimpParser/X/XFileParser.cs, source/OpenBveApi/System/Path.cs, source/OpenBveApi/System/TextEncoding.cs, source/Plugins/Object.DirectX/Parsers/AssimpXParser.cs, source/Plugins/Object.DirectX/Parsers/NewXParser.cs, source/Plugins/Object.DirectX/Plugin.cs
- Fix: a text encoding issue in Assimp X file parser
- Assimp X file parser didn't consider the character encoding of the text format.
- Fix: the issue where some object files specify absolute paths
- For example, the texture is specified as an absolute path on the 1490, 1499, and 1532 lines of `railway\object\marumado\5250.x` on the route published [here](http://marumado.umic.jp/marumado_go_download.php).
=> Fix: some issues with the path of texture file in DirectX file

source/Plugins/Train.OpenBve/Panel/Panel2CfgParser.cs, source/Plugins/Train.OpenBve/Panel/PanelCfgParser.cs, source/Plugins/Train.OpenBve/Panel/PanelXmlParser.cs
From v1.7.3.0, the loading time of some trains will be more than 10 times longer.
Tokyu 5050 series on [here](http://www.nozomi.vc/02_toyoko/index.htm) is that.
The following table shows the results of measuring the loading time on the same route and the same train.
| Version          | Loading time (s) |
| ---------------- | ------------- |
| v1.7.2.4         | 12            |
| **v1.7.3.1**         | **155**       |
| This PR (32 bit) | 12            |
This is because we are pre-loading unnecessary textures.
This train takes a long time to load `[DigitalNumber]` from lines 726 to 751 of Panel2.cfg.
Since the height of `Sub\Target.bmp` is 1024 and `Interval` is 1, we are loading `Sub\Target.bmp` 1024 times [here](https://github.com/leezer3/OpenBVE/blob/7ac627b08c4e771c280ac709a08dbd25475a …
=> Remove: unnecessary pre-loading of textures

source/Plugins/Train.OpenBve/Train/TrainDatParser.cs
[This commit](https://github.com/leezer3/OpenBVE/commit/963dff02aedd24a911431c38ec956e8a69a823aa) hasn't fixed the error yet.
See also: https://bveworldwide.forumotion.com/t2102-render-bugs-with-non-existing-parts-of-railjet-coaches-object-viewer-complaining-of-train-dat-format#20662
=> Fix: the error when parsing Train.dat that doesn't contain version string

source/OpenBVE/System/Options.cs
The default language being English instead of the system language at first startup has been a long-time issue that confuses many new players. It seems the code for language detection still uses CFG when the format of the language files has been changed to XLF, which makes it inoperative.
=> Fix: System language is not used by default

source/InputDevicePlugins/DenshaDeGoInput/Controller.Classic.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs
This adds support for USB adapters which map the direction buttons to two axes (left/right and up/down).
Closes #655
=> Add support for adapters mapping left/right to axis

source/InputDevicePlugins/DenshaDeGoInput/Config.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/InputTranslator.cs
Previously, the plugin handled button repeats internally. This apparently worked well but caused issues like #681 and the code could be simplified. This PR:
1. Closes #681.
2. Improves support for trains with an automatic air brake. When using these trains, the brake handle will reflect the real behaviour more accurately.
=> [DenshaDeGoInput] Fix button repeats and improve brake behaviour

source/OpenBVE/UserInterface/formMain.cs
Currently the program will crash with an Unhandled Windows Form Exception if a connection to the server cannot be established.
This PR should fixes it, though I still have a few questions:
Is that suppose to be a typo?
The original code comment has mentioned that "The internet connection is broken...", so I assume we can't establish a connection to the server.
Also on the [contributing guidelines](https://github.com/leezer3/OpenBVE/blob/aa9f170147fea0f707e21307f9d7469d036d1aff/Contributing.md), it is mentioned to use "Unix (CR LF) line terminators"  
but as far as I am aware Unix only uses LF, and Windows uses CR LF?
=> Fix: Crash when checking for update without an internet connection

source/OpenBveApi/FunctionScripts/AnimationScripts.cs, source/OpenBveApi/FunctionScripts/CSAnimationScript.cs, source/OpenBveApi/FunctionScripts/FunctionScript.cs, source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs, source/OpenBveApi/Objects/ObjectTypes/TrackFollowingObject.cs, source/OpenBveApi/Objects/ObjectTypes/WorldSound.cs, source/OpenBveApi/OpenBveApi.csproj, source/OpenBveApi/System/Path.cs, source/Plugins/Object.Animated/Plugin.Parser.cs
- An argument list can be passed to the constructor of the script class, in a format similar to URL query string. This enables reusing the same script file for multiple purposes, such as doors on both sides, which requires 4 individual script files before.
Example: 
```ini
[Object]
Position = 0, 0, 0
States = test.csv
TranslateZScript = test.cs?value=1
```
```csharp
using System;
using System.Collections.Generic;
using OpenBveApi.Hosts;
using OpenBveApi.Interface;
using OpenBveApi.Math;
using OpenBveApi.Trains;
public class OpenBVEScript {
private int val;
public OpenBVEScript(Dictionary<string, string> args) {
val = int.Parse(args["value"]);
}
public double ExecuteScript(AbstractTrain Train, int CarIndex, Vector3 Position, double TrackPosition, 
int SectionIndex, bool IsPartOfTrain, …
```
=> Additions to the CSScript animation C# script interface

source/OpenBVE/System/Functions/CrashHandler.cs, source/OpenBVE/UserInterface/formMain.cs
This PR addresses these two issues:
1. `t + Environment.StackTrace` calls `ThreadExceptionEventArgs.ToString()`, which simply returns the string `ThreadExceptionEventArgs` instead of the full message and stack trace, and prevented the actual exception message from being written to log. By the way, according to player reports, "Unhandled Windows Forms Exception" is incredibly common. Their causes are partially unknown due to this issue.
2. In rare circumstances `null` can be present in `Interface.CurrentOptions.RecentlyUsedTrains`, and raises exception in formMain_Load resulting in OpenBVE being unable to start.
=> Fix: UI Thread Exception not written to log

source/CarXMLConvertor/Convert.ExtensionsCfg.cs, source/LibRender2/BaseRenderer.cs, source/OpenBVE/Game/ObjectManager/ObjectManager.cs, source/OpenBVE/Game/Score/Score.cs, source/OpenBVE/Graphics/Renderers/Overlays.Debug.cs, source/OpenBVE/OldCode/TrainManager.cs, source/OpenBVE/UserInterface/formImageExport.cs, source/OpenBVE/UserInterface/formMain.Start.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.CarNode.cs, source/TrainEditor2/IO/Trains/TrainDat/Parser.cs, source/TrainEditor2/Simulation/TrainManager/TrainManager.cs, source/TrainManager/Car/CarBase.cs, source/TrainManager/Cargo/CargoBase.cs, source/TrainManager/Cargo/NoLoad.cs, source/TrainManager/Cargo/Passengers.cs, source/TrainManager/Cargo/RobustFreight.cs, source/TrainManager/Train/Station.cs, source/TrainManager/Train/TrainBase.cs, source/TrainManager/TrainManager.cs, source/TrainManager/TrainManager.csproj
* Moves cargo to be an abstract type on a per-car as opposed to per-train basis.
* Implements cars which carry no cargo.
BVE assumes that all cars carry passengers, and hence thier mass is updated according to the passenger ratio when stopping at a station.
This isn't valid for locomotives, and isn't really helpful if we're trying to move beyond our current bounds (for example, later we might want station specific cargo)
Small baby steps at the minute- Fuel usage needs to be implemented for motor cars (if appropriate), but that will feed into another modification of the mass figure, and should not be done as a cargo type; otherwise we'd need far more subtypes.
=> Change: Move to an abstract cargo type

source/CarXMLConvertor/Convert.ExtensionsCfg.cs, source/CarXMLConvertor/Convert.TrainDat.cs, source/OpenBVE/System/Input/Keyboard.cs, source/OpenBVE/System/MainLoop.cs, source/Plugins/Train.OpenBve/Train.OpenBve.csproj, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.AccelerationNode.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.BrakeNode.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.CarNode.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.HandleNode.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.cs, source/TrainManager/Handles/AbstractHandle.cs, source/TrainManager/Handles/Handles.Brake.cs, source/TrainManager/Handles/Handles.Power.cs, source/TrainManager/Handles/Handles.SpringTypes.cs, source/TrainManager/TrainManager.csproj
A relatively common feature of prototype power / brake handles is a spring feature.
This gradually returns the handle to a 'default' position after a set period of time. 
This PR implements this, along with some missing XML plumbing for setting the number of power / brake notches.
- Allows the driver car to be set via the train.xml
- Allows the number of brake notches to be set via XML using the _Train --> Car --> Brake --> Handle --> Notches_ **NOTE:** The number of brake notches is only set via the driver car (values set on other cars will be ignored)
- A brake handle spring delay in seconds may be set in XML via _Train --> Car --> Brake --> Handle --> SpringTime_ - Each time the timer elapses, the brake will be increased by one notch. Interacting with the handle resets the timer.
- The …
=> New: Implement sprung handle types

source/OpenBVE/System/Loading.cs, source/TrainManager/SafetySystems/Plugin/Plugin.cs, source/TrainManager/Train/Doors.cs
Before sending data to input device plugins, check whether the train is the player's train. Unlike train plugins, only the player's train is relevant.
Fixes #796
=> Only send data from player train to input device plugins

source/OpenBveApi/System/Path.cs
It is noticed that the addition of one more argument in #696 breaks compatibility with some ATS plugins making use of this method. This fixes that.
=> Fix ATS plugin compatibility broken due to method signature change

source/RouteViewer/ProgramR.cs
Colored Rail Path Form would get disposed if closed without pressing the "close" button (Rather than setting the form to null)
This will result in a crash when pressing P after closing (Cannot access a disposed object)
=> Fix: Colored Rail Path Form crash

source/CarXMLConvertor/Convert.ExtensionsCfg.cs, source/ObjectViewer/FunctionScripts.cs, source/OpenBVE/Game/ObjectManager/AnimatedObjects/FunctionScripts.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBveApi/FunctionScripts/FunctionScript.cs, source/OpenBveApi/FunctionScripts/Instructions.cs, source/OpenBveApi/Runtime/Train/ElapseData.cs, source/OpenBveApi/Runtime/Train/VehicleSpecs.cs, source/Plugins/Train.OpenBve/Train/BVE/TrainDatParser.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.cs, source/RouteViewer/FunctionScripts.cs, source/TrainManager/SafetySystems/Plugin/NetPlugin.cs, source/TrainManager/SafetySystems/Plugin/Plugin.Functions.cs, source/TrainManager/SafetySystems/Plugin/Plugin.cs, source/TrainManager/SafetySystems/TrainSafetySystems.cs, source/TrainManager/Train/LightSource.cs, source/TrainManager/TrainManager.csproj
This PR adds a basic headlights animation property.
Simple state based toggle, with function script instruction.
https://bveworldwide.forumotion.com/t2266-how-to-set-the-keyboard-key-for-turn-on-off-lamp-in-statefunction-formula#21235
The keybindings for these exist, & were added several years ago (along with many others....) for plugin usage initially, with the idea that they would eventually be implemented into the sim.
**train.dat** based trains are assumed to have a simple single state on / off headlight.
Requires documentation to be added before merging.
=> New: Add basic headlights animation properties

source/InputDevicePlugins/DenshaDeGoInput/Controller.Zuiki.cs
Recently, a special edition of the Densha de GO! controller for the Nintendo Switch was released, and for some reason they changed the VID, PID and name. This adds support for the controller in DenshaDeGoInput.
=> Add support for ZKNS-002

source/CarXMLConvertor/Convert.ExtensionsCfg.cs, source/CarXMLConvertor/mainForm.Designer.cs, source/CarXMLConvertor/mainForm.cs
This PR fixes some of the bugs and improve the Car XML Converter.  
Nothing major, just found several annoyances when needing to use the program.
- Special characters from **train.txt** not escaped in **train.xml**, leading to in-game crash due to an invalid train xml.
- Encoding is now detected, non-UTF8 encoded **train.txt** should be converted properly.
- `terminatedEarly` not reset between runs, resulting in conversion not working if the first attempt failed.
- Minor changes on the UI, should look slightly nicer now
- Support drag and drop files/folders to the textbox. (Will grab parent directory if it's a file, the folder browser dialog is quite tedious to navigate)
- The log box is now read only rather than disabled, should result in easier readability. (Also allows scrolling)
=> Change: Improve Car XML Converter

source/OpenBveApi/Packages/Packages.Database.cs
A typo caused broken dependencies (For routes) to be listed twice instead of detecting the "Other" package type.
- Fixes Route being displayed twice when listing broken dependencies (Affect others who are consuming the API as well?)
- Fixes Other not being listed for broken dependencies
=> Fix: Wrongly detected broken dependencies

source/InputDevicePlugins/DenshaDeGoInput/Config.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Classic.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Ps2.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Unbalance.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Zuiki.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/Help.cs, source/InputDevicePlugins/DenshaDeGoInput/LibUsb.cs
https://bveworldwide.forumotion.com/t2345-densha-de-go-controller-plugin-not-registering-controller#21523
@MarcRiera - This should solve the reported issue, but your thoughts on this design may be interesting.
Basically switches to using a constructed class and a nice human readable enum to switch controller type.
Also adds some log messages if we encounter an unknown PID from the recognised VID list.
Not sure on the names for the unbalance enum members, you'll have to comment on those :)
=> Change: Improve DenshaDeGo! Input usb mapping

source/OpenBVE/UserInterface/formMain.Designer.cs, source/OpenBVE/UserInterface/formMain.Packages.cs
On some fonts like Noto Sans CJK, the font height is higher than it should be.
Some label or button does not have enough height to show the font, and on some system it will refuse to show the text if there's not enough height to display the font.
This PR should fix most of the issues and get the text to re-appear again.
Though System.Windows.Forms.MessageBox may still have invisible text button, but that's out of our control I think.
Fixes #875
=> Fix: Increase height of WinForm controls

source/OpenBveApi/Runtime/Runtime.cs, source/OpenBveApi/Runtime/System/LoadProperties.cs, source/TrainManager/SafetySystems/Plugin/NetPlugin.cs
This adds a further function to the runtime API- PlayMultiCarSound
Allows an array of car indices to be passed allowing for multiple of the same sound to be created in one go.
Needs testing, and will require modifications to the sample plugin.
=> New: Add overload to play multi-car sounds

source/LibRender2/Screen/InterfaceType.cs, source/OpenBVE/Game/Menu/Menu.cs, source/OpenBVE/Graphics/Renderers/Overlays.cs, source/OpenBVE/System/Input/Keyboard.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/OpenBVE/System/MainLoop.cs
https://github.com/leezer3/OpenBVE/pull/918
Actually specifies the GL main menu as a different interface type, allowing special handling where required.
=> Change: Actually specificy GL main menu as a different interface type

source/OpenBVE/Game/Menu/Menu.cs
This PR prevents the Start Game/Choose Train button to proceed without a route being processed or a train being selected first
Fix #927.
=> Fix: Disable GL Main Menu Start button if route/train not selected

source/OpenBVE/System/Input/ProcessControls.Digital.cs, source/TrainManager/Car/Systems/Sanders.cs
#931
Keyboard repeating input would make the sander toggle on and off repeatedly with `PressAndHold`, this PR fixes that.
Sanders will still only update when power is applied which may lead to oddities when toggled manually, although I am afraid that's not something I am qualified to tweak with...
=> Fix: Sander toggle behavior

source/OpenBVE/System/GameWindow.cs
Introduced in https://github.com/leezer3/OpenBVE/commit/17ffa6246575a5dbf10eca25a19eb4036848ceb6
=> Remove memory debug message when running in 32-bit

source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/LibUsb.UsbController.cs, source/InputDevicePlugins/DenshaDeGoInput/LibUsb.cs
This PR fixes a mapping issue caused by an off-by-one error. Also improves detection of PS2 controllers, which previously had a fixed endpoint.
Fixes #952
=> Fix mapping for Densha de GO! controllers

source/OpenBVE/Audio/Sounds.Update.cs, source/OpenBveApi/Sounds/Sounds.SoundSourceState.cs, source/RouteViewer/Audio/Sounds.Update.cs, source/SoundManager/Sounds.CarSound.cs, source/SoundManager/Sounds.SoundSource.cs, source/TrainEditor2/Simulation/TrainManager/Car/Car.cs, source/TrainManager/Car/CarBase.cs
This experimental PR pauses rather than stops the **Flange** and **Run** sounds.
May allow over-length sounds to work a little better by stopping repetition glitches.
[PauseResume.zip](https://github.com/leezer3/OpenBVE/files/13451367/PauseResume.zip)
**NOTES:**
* Currently applies to all content. Unlikely to require restricting to BVE stuff, as this seems a logical addition.
* If merged, requires an errata note for changed behaviour.
* When resumed, volume is at the set volume, not the original volume.
=> Change: Pause rather than stop flange / run loops

source/OpenBVE/UserInterface/formBugReport.cs
Fixes a regression from #972, where the translation path from the bug report dialog are mistakenly converted, resulting in no text in the bug report section.
=> Fix: No translation/text in the Bug Report Dialog

assets/Languages/en-US.xlf, source/InputDevicePlugins/DenshaDeGoInput/Config.Designer.cs, source/InputDevicePlugins/DenshaDeGoInput/Config.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Ps2Ddgo.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Ps2TS.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Unbalance.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.Zuiki.cs, source/InputDevicePlugins/DenshaDeGoInput/Controller.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.cs, source/InputDevicePlugins/DenshaDeGoInput/DenshaDeGoInput.csproj, source/InputDevicePlugins/DenshaDeGoInput/Drivers/99-ps2-train-controllers.rules, source/InputDevicePlugins/DenshaDeGoInput/Drivers/MTC.cfg, source/InputDevicePlugins/DenshaDeGoInput/Drivers/TrainMascon.cfg, source/InputDevicePlugins/DenshaDeGoInput/InputTranslator.cs, source/InputDevicePlugins/DenshaDeGoInput/LibUsb.UsbController.cs, source/InputDevicePlugins/DenshaDeGoInput/LibUsb.cs
- Add support for the Multi Train Controller (all cartridges).
- Add support for the Train Mascon.
- Add more PIDs from Zuiki and allow unrecognised PIDs as long as they have the required capabilities (fixes #995).
- Check for minimum capabilities for OpenTK joysticks, in case a malformed joystick with the same VID/PID is used.
- Internal refactor of control handling to pass the main program only the commands actually used (fixes buttons not working in some cases).
- Assigned commands for buttons are now stored by ID instead of index, requiring the user to define them from scratch when updating from a previous version.
- udev rules need to be installed again for the Multi Train Controller/Train Mascon to work.
=> Densha de GO! Input: fixes and support for MTC

source/InputDevicePlugins/DenshaDeGoInput/Controller.cs
Because there are platform differences regarding joystick GUID format in OpenTK and Wine was not accounted for, OpenBVE has been unable to detect certain Densha de GO! controllers when running under Wine.
This ensures joystick GUIDs are treated like under Windows if the host platform is Wine.
=> Fix Wine support for Densha de GO! Input

source/OpenBVE/System/Functions/CrashHandler.cs, source/OpenBveApi/System/FileSystem.cs, source/TrainEditor2/Models/App.cs
This PR changes the date format to `yyyy-MM-dd HH:mm:ss` when printed in OpenBVE Logs/Crash Logs, as oppose to the current behavior which varies between system locales.
This should reduce ambiguity, especially relating to places with **mm/dd** vs **dd/mm** (Not that it has happened in a puzzling manner... yet, but seems like a good idea anyway)
=> Change: Standardize date format in logs

assets/Compatibility/RoutePatches/Indonesia.xml, assets/Compatibility/RoutePatches/database.xml, source/OpenBVE/Game/ObjectManager/ObjectManager.cs, source/OpenBveApi/Objects/ObjectTypes/AnimatedObject.cs, source/OpenBveApi/System/BaseOptions.cs, source/Plugins/Object.Animated/Plugin.Parser.cs, source/Plugins/Object.LokSim/GroupParser.cs, source/Plugins/Object.Msts/ShapeParser.cs, source/Plugins/Route.CsvRw/Compatability/RoutefilePatch.cs, source/Plugins/Route.CsvRw/XML/RoutePatchDatabase.cs
https://github.com/leezer3/OpenBVE/issues/955
The (essential) cause of the above issue is that it uses large numbers of animated objects, all of which contain functions which are costly to execute. 
The game executes a forced update on all world animated objects in the two following circumstances:
* At game start
* After a jump (manual / change ends)
If our world contains thousands of animated objects, each of which contains one or more heavy functions, this can bog down significantly, and cause the slow loading above.
This PR does the following:
* Implements a custom equality operator for animated objects. (This speeds up some aspects of the update)
* On a forced update, only objects placed within 5km of the camera position or having a **TrackFollowerFunction** will be evaluated. 
This …
=> Experimental: Improve forced updates when large numbers of Animated Objects are present

source/InputDevicePlugins/DenshaDeGoInput/Help.cs
I forgot to link the MTC drivers in the GUI, sorry. This closes #1038.
=> Fix: Add missing MTC drivers to GUI

source/OpenBVE/System/GameWindow.cs
`PreloadTextures()` was called without checking whether the game has launched into the new GL Menu or not, causing a crash as there's no train in the menu.
Moving to SetupSimulation should make more sense.
Fixes #1054
=> Fix: Crash when launching with GL Menu

assets/Languages/ca-ES.xlf, assets/Languages/cs-CZ.xlf, assets/Languages/de-CH.xlf, assets/Languages/de-DE.xlf, assets/Languages/en-GB.xlf, assets/Languages/en-US.xlf, assets/Languages/es-ES.xlf, assets/Languages/fi-FI.xlf, assets/Languages/fr-FR.xlf, assets/Languages/hu-HU.xlf, assets/Languages/id-ID.xlf, assets/Languages/it-IT.xlf, assets/Languages/ja-JP.xlf, assets/Languages/ko-KR.xlf, assets/Languages/ms_MY.xlf, assets/Languages/nb_NO.xlf, assets/Languages/nl-NL.xlf, assets/Languages/pl-PL.xlf, assets/Languages/pt-BR.xlf, assets/Languages/pt-PT.xlf, assets/Languages/ro-RO.xlf, assets/Languages/ru-RU.xlf, assets/Languages/sk-SK.xlf, assets/Languages/uk-UA.xlf, assets/Languages/zh-CN.xlf, assets/Languages/zh-HK.xlf, assets/Languages/zh-TW.xlf, source/OpenBVE/UserInterface/formMain.Packages.cs
This PR:
- Reformat all XLIFF documents
- Synchronize `<source>` text and missing entries from en-US.xlf to all files
- Rename all instance of `openBVE` to `OpenBVE`
- Rename duplicated entry id (Those within the same group that is, which makes it unidentifiable)
- - `train_default`, `train_default_yes` and `train_default_no` is moved to `menu` group, fixes empty dialog box in the GL Menu when asked whether to use the route's default train.
- - `creation_header` has been split to `creation_header` (Create a package) and `enter_details_header` (Enter package details)
**Motivation:**
Transifex does not seems to be in sync anymore and no new translation appears. It also seems to untranslate duplicated units id across groups (Which is technically correct as defined by XLIFF specs), as such …
=> Translation Files Cleanup

debian/openbve.desktop
The desktop launcher used for Linux still had the old name without the initial caps. I have also translated the comment and generic name to Catalan.
=> Update Linux desktop launcher

source/OpenBveApi/Runtime/Route/Station.cs, source/TrainManager/SafetySystems/Plugin/Plugin.cs
This PR changes the runtime API's `Station` class to include properties for forward/backward tolerance. It is now possible, for example, to simulate an ATC system that prevents doors from opening outside specific stop areas.
The old constructor's signature is intact for compatibility with existing plugins.
Closes #1076
=> Train plugins: include forward/backward tolerance in elapseData

assets/Languages/en-US.xlf, source/ObjectViewer/Hosts.cs, source/ObjectViewer/InterfaceS.cs, source/ObjectViewer/ProgramS.cs, source/ObjectViewer/System/GameWindow.cs, source/ObjectViewer/Trains/NearestTrain.cs, source/OpenBVE/Game/AI/AI.SimpleHuman.cs, source/OpenBVE/Game/Game.cs, source/OpenBVE/Game/RouteInfoOverlay.cs, source/OpenBVE/Game/TrainManager.cs, source/OpenBVE/System/GameWindow.cs, source/OpenBVE/System/Host.cs, source/OpenBVE/System/Loading.cs, source/OpenBVE/System/Program.cs, source/OpenBveApi/OpenBveApi.csproj, source/OpenBveApi/System/Hosts/HostInterface.cs, source/OpenBveApi/Train/AbstractTrain.cs, source/OpenBveApi/Train/TrainState.cs, source/OpenBveApi/Train/TrainType.cs, source/RouteViewer/GameR.cs, source/RouteViewer/System/Host.cs, source/RouteViewer/TrainManagerR.cs, source/TrainManager/Brake/AirBrake/AutomaticAirBrake.cs, source/TrainManager/Brake/AirBrake/ElectromagneticStraightAirBrake.cs, source/TrainManager/Car/CarBase.cs, source/TrainManager/TrackFollowingObject/ScriptedTrain.cs, source/TrainManager/Train/TrainBase.cs, source/TrainManager/TrainManager.cs
This PR allows us to couple to loose cars that we've previously dropped.
Currently, driving into a train with both at less than the critical collision speed (this is a fixed 8km/h value) will couple us.
Heavy WIP, but now appears to be working correctly.
* Trains need a way of distinguishing what they are. TFOs have this already by virtue of being a different type, but it's not quite right.
* Need to implement a 'do you wish to couple' yes / no dialog.
* It would be useful to allow us to place loose cars independantly on the route (sidings etc) so we could pick them up - Cars from the train.xml format would seem to fit this bill, as they should contain most if not all of the properties required. Would also require a new routefile command (Single XML, containing all loose cars??) Possibly …
=> New: Allow coupling

source/OpenBVE/System/GameWindow.cs, source/OpenBVE/System/Loading.cs, source/Plugins/Train.OpenBve/Panel/PanelAnimatedXmlParser.cs, source/Plugins/Train.OpenBve/Plugin.cs, source/Plugins/Train.OpenBve/Train/BVE/ExtensionsCfgParser.cs, source/Plugins/Train.OpenBve/Train/XML/TrainXmlParser.cs
This PR improves the progress bar of the train section in the loading screen, which for some time now cannot reach to 100%:
- Add missing progress increment in PanelAnimatedXmlParser
- Add progress reporting when loading train.xml/extensions.cfg
- Fix `CurrentTrain` counter getting incremented when loading train plugins rather than when loading trains
=> Improve train loading progress bar

source/OpenBVE/Game/MessageManager.TextualMessages.cs, source/OpenBVE/Game/MessageManager.cs, source/OpenBVE/Game/Score/Score.cs, source/OpenBVE/Graphics/Renderers/Overlays.ScoreMessages.cs, source/OpenBVE/System/GameWindow.cs, source/OpenBVE/System/Host.cs, source/OpenBVE/System/Input/ProcessControls.Digital.cs, source/OpenBVE/System/Input/ProcessControls.cs, source/RouteManager2/MessageManager/AbstractMessage.cs, source/RouteManager2/MessageManager/MessageTypes/GeneralMessage.cs, source/RouteManager2/MessageManager/MessageTypes/MarkerImage.cs, source/RouteManager2/MessageManager/MessageTypes/TextureMessage.cs, source/RouteViewer/Game/MessageManager.cs, source/RouteViewer/System/Gamewindow.cs, source/TrainManager/SafetySystems/Plugin/NetPlugin.cs
Message timeouts are currently expressed as an in-game time.
This however causes issues when time acceleration is used, as a message will stay on-screen for 5 times less than intended.
This PR changes the timeouts to be an exact real-time, using the RealTimeElapsed variable, not the in-game time.
Message timeouts are also now not updated whilst in the in-game menu.
Doing this as a PR as it touches a whole bunch of code, and I want to double-check things.....
Marginally related:
https://github.com/leezer3/OpenBVE/issues/1182
(I appear to have first noticed this 4 years ago and promptly forgot about it...)
=> Make message timeouts independent of game speed
